import { CountyData, EthnicGroup, TerrainArchetype, WeatherType } from '../types';

interface RawCountyInput {
  id: string;
  name: string;
  prefecture: string;
  isAutonomous?: boolean;
  ethnicGroup?: EthnicGroup;
  altitude: number;
  mapCoord: { x: number; y: number; elevation: number };
  terrainArchetype: TerrainArchetype;
  terrainType: string;
  terrainDescription: string;
  naturalLandmark: { name: string; description: string; tag: string };
  culturalLandmark: { name: string; description: string; tag: string };
  ethnicFeatures: { costumes: string; crafts: string; traditions: string; specialty: string };
  weather?: WeatherType;
}

const archetypePalettes: Record<TerrainArchetype, { skyTop: string; skyBottom: string; mountainFar: string; mountainMid: string; ground: string; accent: string }> = {
  meadow: { skyTop: '#1e3a8a', skyBottom: '#93c5fd', mountainFar: '#cbd5e1', mountainMid: '#64748b', ground: '#365314', accent: '#eab308' },
  danxia: { skyTop: '#7c2d12', skyBottom: '#fdba74', mountainFar: '#9a3412', mountainMid: '#c2410c', ground: '#78350f', accent: '#fb923c' },
  forest: { skyTop: '#1e293b', skyBottom: '#64748b', mountainFar: '#94a3b8', mountainMid: '#334155', ground: '#14532d', accent: '#22c55e' },
  glacier: { skyTop: '#0f172a', skyBottom: '#38bdf8', mountainFar: '#f8fafc', mountainMid: '#7dd3fc', ground: '#bae6fd', accent: '#38bdf8' },
  gobi: { skyTop: '#451a03', skyBottom: '#fde047', mountainFar: '#78350f', mountainMid: '#a16207', ground: '#713f12', accent: '#f59e0b' },
  loess: { skyTop: '#78350f', skyBottom: '#fed7aa', mountainFar: '#a16207', mountainMid: '#b45309', ground: '#854d0e', accent: '#ea580c' },
  saltlake: { skyTop: '#0c4a6e', skyBottom: '#a5f3fc', mountainFar: '#e0f2fe', mountainMid: '#38bdf8', ground: '#f0fdfa', accent: '#06b6d4' },
  canyon: { skyTop: '#312e81', skyBottom: '#c7d2fe', mountainFar: '#4338ca', mountainMid: '#6366f1', ground: '#1e1b4b', accent: '#818cf8' },
};

function createGansuCounty(raw: RawCountyInput): CountyData {
  return {
    ...raw,
    province: '甘肃',
    isAutonomous: raw.isAutonomous ?? false,
    ethnicGroup: raw.ethnicGroup ?? '汉族/多元',
    weather: raw.weather ?? (raw.altitude > 3500 ? 'light_snow' : raw.terrainArchetype === 'gobi' ? 'mist' : 'clear'),
    bgPalette: archetypePalettes[raw.terrainArchetype],
  };
}

export const GANSU_COUNTIES: CountyData[] = [
  // 1. 兰州市 (8)
  createGansuCounty({
    id: 'chengguan_lz', name: '城关区', prefecture: '兰州市', altitude: 1520,
    mapCoord: { x: 0.35, y: -0.05, elevation: 0.35 }, terrainArchetype: 'canyon',
    terrainType: '黄河穿城金城盆地与两山对峙峡谷',
    terrainDescription: '黄河如奔雷穿城而过，白塔山与皋兰山两峰夹峙，自古丝路重镇。',
    naturalLandmark: { name: '白塔山与黄河九曲风情线', description: '俯瞰金城黄河奔流与白塔倒影。', tag: '金城母亲河' },
    culturalLandmark: { name: '兰州铁桥（中山桥）', description: '清光绪年间建造的黄河第一铁桥。', tag: '黄河第一桥' },
    ethnicFeatures: { costumes: '西北汉族朴素短褐与羊皮袄', crafts: '兰州刻葫芦技艺', traditions: '太平鼓阵', specialty: '兰州牛肉拉面、冬果梨' },
  }),
  createGansuCounty({
    id: 'qilihe', name: '七里河区', prefecture: '兰州市', altitude: 1580,
    mapCoord: { x: 0.34, y: -0.06, elevation: 0.36 }, terrainArchetype: 'loess',
    terrainType: '阿干古镇煤峡与南山百合梯田',
    terrainDescription: '黄土低山丘陵与石佛沟原始落叶松峡谷相连。',
    naturalLandmark: { name: '石佛沟国家森林公园', description: '峰峦叠嶂，林木葱茏。', tag: '林海幽谷' },
    culturalLandmark: { name: '阿干镇古窑址', description: '宋明瓷窑重镇遗址。', tag: '陶窑重镇' },
    ethnicFeatures: { costumes: '农耕花布袄袍', crafts: '百合古法晾晒培植', traditions: '花儿民歌会', specialty: '兰州甜百合' },
  }),
  createGansuCounty({
    id: 'xigu', name: '西固区', prefecture: '兰州市', altitude: 1560,
    mapCoord: { x: 0.32, y: -0.05, elevation: 0.35 }, terrainArchetype: 'canyon',
    terrainType: '黄河八盘峡水峡与沿江古渡',
    terrainDescription: '黄河出刘家峡后入八盘峡，石壁高耸，江水如练。',
    naturalLandmark: { name: '八盘峡库区湿地', description: '芦苇丛生，水鸟翔集。', tag: '高峡平湖' },
    culturalLandmark: { name: '金城关与柴家台渡口', description: '古代丝路水运重要通衢。', tag: '古道津渡' },
    ethnicFeatures: { costumes: '渡口水手短衫', crafts: '黄河羊皮筏子扎制', traditions: '船夫号子', specialty: '金城热冬果' },
  }),
  createGansuCounty({
    id: 'anning', name: '安宁区', prefecture: '兰州市', altitude: 1530,
    mapCoord: { x: 0.33, y: -0.04, elevation: 0.35 }, terrainArchetype: 'danxia',
    terrainType: '天斧沙宫风蚀红砂岩峡谷',
    terrainDescription: '砂石山峰风蚀形如宫殿楼宇，落日余晖下金碧辉煌。',
    naturalLandmark: { name: '天斧沙宫地质奇观', description: '红砂岩奇峰如古堡林立。', tag: '天斧鬼斧' },
    culturalLandmark: { name: '仁寿山古寿阁', description: '十里桃乡掩映古刹神庙。', tag: '十里桃川' },
    ethnicFeatures: { costumes: '果农素衣布鞋', crafts: '百年白凤桃嫁接技艺', traditions: '桃花诗会', specialty: '安宁白凤桃' },
  }),
  createGansuCounty({
    id: 'honggu', name: '红古区', prefecture: '兰州市', altitude: 1680,
    mapCoord: { x: 0.28, y: -0.04, elevation: 0.38 }, terrainArchetype: 'canyon',
    terrainType: '湟水下游河谷与红层岩崖',
    terrainDescription: '甘青两省交界要津，湟水滚滚注入大通河。',
    naturalLandmark: { name: '湟水河谷红层峡', description: '红层泥岩在河畔如霞光铺染。', tag: '湟水交汇' },
    culturalLandmark: { name: '马家窑彩陶古文化遗址', description: '出土珍贵旋涡纹双耳彩陶瓮。', tag: '马家窑祖源' },
    ethnicFeatures: { costumes: '河湟农家袄', crafts: '彩陶旋涡泥模烧制', traditions: '彩陶祭舞', specialty: '红古黑瓜子' },
  }),
  createGansuCounty({
    id: 'yongdeng', name: '永登县', prefecture: '兰州市', altitude: 2050,
    mapCoord: { x: 0.26, y: 0.02, elevation: 0.45 }, terrainArchetype: 'forest',
    terrainType: '吐鲁沟奇石林海与大通河大峡谷',
    terrainDescription: '祁连山支脉冷杉繁茂，奇峰擎天，幽谷飞泉。',
    naturalLandmark: { name: '吐鲁沟国家森林公园', description: '峰峦奇秀似华山，林深似九寨。', tag: '吐鲁神秀' },
    culturalLandmark: { name: '鲁土司衙门旧址', description: '全国保存最完整的明清明代土司建筑群。', tag: '西北第一土司' },
    ethnicFeatures: { costumes: '明清土司仪服与满汉长袍', crafts: '苦水玫瑰古法蒸馏精油', traditions: '玫瑰花节', specialty: '永登苦水玫瑰' },
  }),
  createGansuCounty({
    id: 'gaolan', name: '皋兰县', prefecture: '兰州市', altitude: 1720,
    mapCoord: { x: 0.36, y: 0.01, elevation: 0.40 }, terrainArchetype: 'loess',
    terrainType: '黄河奇峡与百年古梨园沙地',
    terrainDescription: '黄河自青藏奔涌而下，河湾深沉，沃野藏梨。',
    naturalLandmark: { name: '什川世界第一古梨园', description: '数万株明清古梨树沿河苍翠。', tag: '万亩梨云' },
    culturalLandmark: { name: '黄河三峡飞桥古渡', description: '扼守北去宁夏古道重津。', tag: '黄河古道' },
    ethnicFeatures: { costumes: '老羊皮靠背褂', crafts: '古树高架嫁接与云梯修枝', traditions: '鼓子秧歌', specialty: '什川冬果梨' },
  }),
  createGansuCounty({
    id: 'yuzhong', name: '榆中县', prefecture: '兰州市', altitude: 2180,
    mapCoord: { x: 0.38, y: -0.08, elevation: 0.48 }, terrainArchetype: 'forest',
    terrainType: '兴隆山高山云杉林海与栖云峰奇谷',
    terrainDescription: '陇右名山，白雪映冷杉，成吉思汗曾设行宫于此。',
    naturalLandmark: { name: '兴隆山国家级自然保护区', description: '两峰相对，古木参天，云雾生风。', tag: '陇右第一名山' },
    culturalLandmark: { name: '成吉思汗行宫遗迹与太白泉', description: '青砖石道记录帝王西征驻跸。', tag: '汗王西征' },
    ethnicFeatures: { costumes: '高山道服与陇右棉坎肩', crafts: '松木木雕雕版', traditions: '朝山香会', specialty: '榆中高原夏菜' },
  }),

  // 2. 嘉峪关市 (1)
  createGansuCounty({
    id: 'jiayuguan', name: '嘉峪关市', prefecture: '嘉峪关市', altitude: 1700,
    mapCoord: { x: -0.32, y: 0.52, elevation: 0.42 }, terrainArchetype: 'gobi',
    terrainType: '黑山峡谷与戈壁雄关要塞',
    terrainDescription: '祁连雪峰与黑山石峡相对，天下第一雄关横亘戈壁。',
    naturalLandmark: { name: '黑山摩崖浅石刻与断壁奇谷', description: '戈壁绝壁上的古代游牧猎马石刻。', tag: '黑山石魂' },
    culturalLandmark: { name: '嘉峪关关城与悬壁长城', description: '明代万里长城西端起点，雄伟险峻。', tag: '天下第一雄关' },
    ethnicFeatures: { costumes: '明代长城铁甲与战袍', crafts: '嘉峪关风雨雕石艺', traditions: '烽火台巡防点阅', specialty: '嘉峪关烤羊肉' },
  }),

  // 3. 金昌市 (2)
  createGansuCounty({
    id: 'jinchuan', name: '金川区', prefecture: '金昌市', altitude: 1500,
    mapCoord: { x: 0.05, y: 0.32, elevation: 0.38 }, terrainArchetype: 'gobi',
    terrainType: '龙首山赤岩与戈壁镍都岩原',
    terrainDescription: '戈壁荒原中突兀而起的矿岩山岭，金光烁烁。',
    naturalLandmark: { name: '金川国家矿山公园巨型露天矿坑', description: '地壳深处矿脉展露的磅礴奇观。', tag: '大地金石' },
    culturalLandmark: { name: '三角城沙井文化遗址', description: '青铜时代的北方游牧民族城邑。', tag: '沙井青铜' },
    ethnicFeatures: { costumes: '工矿坚韧工装与皮围裙', crafts: '金镍合金精工雕饰', traditions: '紫金花海节', specialty: '双湾西瓜' },
  }),
  createGansuCounty({
    id: 'yongchang', name: '永昌县', prefecture: '金昌市', altitude: 1980,
    mapCoord: { x: 0.02, y: 0.28, elevation: 0.46 }, terrainArchetype: 'meadow',
    terrainType: '祁连北坡御山峡与高山草场',
    terrainDescription: '北扼龙首，南控祁连雪峰，古道水草肥美。',
    naturalLandmark: { name: '祁连北麓西大河水库与草场', description: '雪水汇成碧波，映照祁连群山。', tag: '雪岭清波' },
    culturalLandmark: { name: '骊靬古城与圣容寺唐代石佛', description: '古罗马战俘东迁传奇与千年古石佛殿。', tag: '骊靬传奇' },
    ethnicFeatures: { costumes: '带异域罗马缀饰的传统毡袍', crafts: '永昌剪纸与木雕佛像', traditions: '骊靬文化节', specialty: '永昌羊肉七寸子' },
  }),

  // 4. 白银市 (5)
  createGansuCounty({
    id: 'baiyin_qu', name: '白银区', prefecture: '白银市', altitude: 1650,
    mapCoord: { x: 0.42, y: 0.02, elevation: 0.39 }, terrainArchetype: 'loess',
    terrainType: '黄土低山红砂石矿谷',
    terrainDescription: '黄土层覆盖下的铜硫矿山，风沙猎猎。',
    naturalLandmark: { name: '火焰山露天矿古遗迹', description: '千岩万壑在红褐中绵延。', tag: '赤矿地裂' },
    culturalLandmark: { name: '水川黄河湿地公园', description: '黄河臂弯中的江南水乡。', tag: '塞上江南' },
    ethnicFeatures: { costumes: '铜矿工短布襟', crafts: '铜锡手打茶壶', traditions: '黄河赛艇会', specialty: '白银大峡枣' },
  }),
  createGansuCounty({
    id: 'pingchuan', name: '平川区', prefecture: '白银市', altitude: 1540,
    mapCoord: { x: 0.48, y: 0.05, elevation: 0.38 }, terrainArchetype: 'canyon',
    terrainType: '屈吴山松涛与黄土台原',
    terrainDescription: '山峦叠嶂，云杉掩映，古代烽烟关隘。',
    naturalLandmark: { name: '屈吴山万亩云杉原始林海', description: '干旱黄土中的翠绿肺叶。', tag: '旱原翠嶂' },
    culturalLandmark: { name: '打拉池红军会师旧址与鹯阴城古渡', description: '西征红军突破黄河处。', tag: '古渡战云' },
    ethnicFeatures: { costumes: '陕甘红军粗布衣', crafts: '黑陶粗碗古窑', traditions: '皮影折子戏', specialty: '平川黑驴肉' },
  }),
  createGansuCounty({
    id: 'jingyuan', name: '靖远县', prefecture: '白银市', altitude: 1390,
    mapCoord: { x: 0.45, y: 0.08, elevation: 0.35 }, terrainArchetype: 'canyon',
    terrainType: '黄河大拐弯翡翠绿洲河滩',
    terrainDescription: '黄河入甘肃北部最后冲积平原，水肥稻香。',
    naturalLandmark: { name: '乌兰山与法泉寺石窟', description: '石崖峭立，古刹依山凌空。', tag: '法泉飞阁' },
    culturalLandmark: { name: '哈思堡与北城滩汉墓群', description: '汉唐守备黄河战略重堡。', tag: '汉家雄垒' },
    ethnicFeatures: { costumes: '沿河渔猎麻布衫', crafts: '滩羊皮熟制工艺', traditions: '黄河灯会', specialty: '靖远羊羔肉' },
  }),
  createGansuCounty({
    id: 'huining', name: '会宁县', prefecture: '白银市', altitude: 1720,
    mapCoord: { x: 0.52, y: -0.05, elevation: 0.41 }, terrainArchetype: 'loess',
    terrainType: '黄土高坡千沟万壑梁峁',
    terrainDescription: '重重叠叠的黄土梯田，干旱而倔强。',
    naturalLandmark: { name: '桃花山松峰', description: '孤峰耸拔，松柏掩映古阁。', tag: '桃峰耸秀' },
    culturalLandmark: { name: '红军三大主力会宁会师旧址（红军会师塔）', description: '红军长征胜利会师圣地。', tag: '胜利会师' },
    ethnicFeatures: { costumes: '西北厚棉对襟老袄', crafts: '会宁皮影雕刻', traditions: '剪纸窗花', specialty: '会宁亚麻籽油、肉杂烩' },
  }),
  createGansuCounty({
    id: 'jingtai', name: '景泰县', prefecture: '白银市', altitude: 1620,
    mapCoord: { x: 0.36, y: 0.15, elevation: 0.40 }, terrainArchetype: 'danxia',
    terrainType: '黄河石林鬼斧神工峰林峡谷',
    terrainDescription: '古地质运动形成的高耸砂砾岩峰林，气势磅礴。',
    naturalLandmark: { name: '景泰黄河石林国家地质公园', description: '数千仞石柱拔地而起，峡谷深邃。', tag: '天然石林' },
    culturalLandmark: { name: '永泰龟城古城堡', description: '明代保存极为完好的龟形军事古城。', tag: '永泰古龟城' },
    ethnicFeatures: { costumes: '戈壁防沙大斗篷', crafts: '驴皮影骨雕刻', traditions: '古城烽火祭', specialty: '景泰枸杞、石林条山苹果' },
  }),

  // 5. 天水市 (7)
  createGansuCounty({
    id: 'qinzhou', name: '秦州区', prefecture: '天水市', altitude: 1310,
    mapCoord: { x: 0.65, y: -0.22, elevation: 0.36 }, terrainArchetype: 'forest',
    terrainType: '羲皇故里翠微秦岭山地',
    terrainDescription: '山水秀丽，气候温润，为华夏人文始祖伏羲故里。',
    naturalLandmark: { name: '南郭寺千年古柏与春秋古柏泉', description: '杜甫赞誉“老树不知岁”古道场。', tag: '杜少陵诗碑' },
    culturalLandmark: { name: '伏羲庙（太昊宫）', description: '明代皇家敕建始祖伏羲祭祀神庙。', tag: '华夏第一庙' },
    ethnicFeatures: { costumes: '天水传统秦汉宽袖袍', crafts: '天水雕漆技艺', traditions: '公祭伏羲大典', specialty: '天水呱呱、浆水面' },
  }),
  createGansuCounty({
    id: 'maiji', name: '麦积区', prefecture: '天水市', altitude: 1400,
    mapCoord: { x: 0.68, y: -0.20, elevation: 0.38 }, terrainArchetype: 'forest',
    terrainType: '麦积孤峰奇秀与小陇山林海',
    terrainDescription: '红砂岩孤峰拔地，形如农家麦垛，千佛凌空。',
    naturalLandmark: { name: '麦积烟雨与仙人崖奇峰', description: '翠峰突兀，常年云遮雾绕。', tag: '麦积烟雨' },
    culturalLandmark: { name: '麦积山石窟（东方雕塑陈列馆）', description: '中国四大石窟之一，泥塑冠绝天下。', tag: '东方雕塑陈列馆' },
    ethnicFeatures: { costumes: '林间采药素麻衣', crafts: '麦积泥塑临摹古法', traditions: '仙人崖朝山会', specialty: '花牛苹果' },
  }),
  createGansuCounty({
    id: 'qingshui', name: '清水县', prefecture: '天水市', altitude: 1380,
    mapCoord: { x: 0.70, y: -0.16, elevation: 0.37 }, terrainArchetype: 'forest',
    terrainType: '轩辕故里陇山峡谷温泉',
    terrainDescription: '轩辕黄帝诞生地，温泉自古涌流，群山叠翠。',
    naturalLandmark: { name: '清水温泉森林公园', description: '含多种矿物质的高山热泉。', tag: '轩辕神汤' },
    culturalLandmark: { name: '轩辕谷古遗迹', description: '黄帝部落早期活动地洞穴。', tag: '轩辕黄帝故里' },
    ethnicFeatures: { costumes: '上古麻麻长衣', crafts: '扁杆剪纸与竹丝细编', traditions: '拜轩辕祖庙', specialty: '清水核桃、花椒' },
  }),
  createGansuCounty({
    id: 'qinan', name: '秦安县', prefecture: '天水市', altitude: 1350,
    mapCoord: { x: 0.62, y: -0.14, elevation: 0.36 }, terrainArchetype: 'loess',
    terrainType: '葫芦河两岸黄土梯田与成纪古地',
    terrainDescription: '女娲故里，黄土梁峁层层叠叠，盛产鲜桃。',
    naturalLandmark: { name: '兴国寺与显圣池丹霞地', description: '千年银杏与宋代无梁佛殿。', tag: '古刹飞檐' },
    culturalLandmark: { name: '大地湾遗址', description: '距今8000年华夏早期文明摇篮。', tag: '大地湾曙光' },
    ethnicFeatures: { costumes: '秦汉农耕长衫', crafts: '秦安女娲彩陶复原', traditions: '女娲祭典', specialty: '秦安蜜桃、安伏花椒' },
  }),
  createGansuCounty({
    id: 'gangu', name: '甘谷县', prefecture: '天水市', altitude: 1360,
    mapCoord: { x: 0.58, y: -0.18, elevation: 0.37 }, terrainArchetype: 'danxia',
    terrainType: '大像山赤壁千仞与渭水河谷',
    terrainDescription: '华夏第一县，红砂岩悬崖上雕凿巨型石胎泥塑大佛。',
    naturalLandmark: { name: '大像山崖峰', description: '峭壁横空，古柏悬生石隙。', tag: '大像凌虚' },
    culturalLandmark: { name: '大像山摩崖大佛与姜维故里', description: '北魏至盛唐开凿的二十三米巨佛。', tag: '大佛天成' },
    ethnicFeatures: { costumes: '姜维战袍披风风韵', crafts: '甘谷传统纯手工麻鞋', traditions: '大像山佛诞法会', specialty: '甘谷红辣椒' },
  }),
  createGansuCounty({
    id: 'wushan', name: '武山县', prefecture: '天水市', altitude: 1450,
    mapCoord: { x: 0.55, y: -0.19, elevation: 0.39 }, terrainArchetype: 'danxia',
    terrainType: '水帘洞悬崖绝壁与鲁班巧斧奇峰',
    terrainDescription: '丹霞峰峦林立，飞瀑悬流成水帘绝景。',
    naturalLandmark: { name: '水帘洞与试斧山天险', description: '天然绝壁如挂巨幕水帘。', tag: '水帘飞雪' },
    culturalLandmark: { name: '拉梢寺世界第一摩崖浮雕大佛', description: '峭壁上浮雕高达42米的大佛像。', tag: '拉梢巨佛' },
    ethnicFeatures: { costumes: '玉雕匠人厚皮围腰', crafts: '武山鸳鸯玉（夜光杯石材）雕刻', traditions: '武山旋鼓舞', specialty: '鸳鸯玉雕刻' },
  }),
  createGansuCounty({
    id: 'zhangjiachuan', name: '张家川回族自治县', prefecture: '天水市', altitude: 1680,
    isAutonomous: true, ethnicGroup: '回族',
    mapCoord: { x: 0.72, y: -0.12, elevation: 0.42 }, terrainArchetype: 'meadow',
    terrainType: '陇山关山高山杜鹃草甸与林海',
    terrainDescription: '地跨关山要塞，高山牧场水草丰茂，林深泉清。',
    naturalLandmark: { name: '关山原始森林与马鹿保护区', description: '草原如织，群峰披绿。', tag: '关山胜景' },
    culturalLandmark: { name: '马家塬战国西戎贵族墓地', description: '出土奢华罕见的战国黄金彩绘车辆。', tag: '西戎黄金车' },
    ethnicFeatures: { costumes: '素白平顶回帽、绣花盖头', crafts: '回族手工牛皮鞍具与铜茶炊', traditions: '开斋盛宴、花儿清唱', specialty: '张家川手抓肉、十三花宴席' },
  }),

  // 6. 武威市 (4)
  createGansuCounty({
    id: 'liangzhou', name: '凉州区', prefecture: '武威市', altitude: 1530,
    mapCoord: { x: 0.12, y: 0.22, elevation: 0.38 }, terrainArchetype: 'gobi',
    terrainType: '河西走廊古凉州绿洲与祁连遥望荒原',
    terrainDescription: '“通一线于广漠，控五霸之天府”，凉州词传唱千载。',
    naturalLandmark: { name: '石羊河源头湿地', description: '雪山融水润泽沙漠绿洲。', tag: '绿洲甘泉' },
    culturalLandmark: { name: '雷台汉墓（马踏飞燕出土地）与凉州文庙', description: '中国旅游标志铜奔马之故乡。', tag: '马踏飞燕' },
    ethnicFeatures: { costumes: '汉唐儒雅凉州客袍', crafts: '西夏文字木活字与铜雕', traditions: '凉州攻鼓子', specialty: '武威三套车（行面/腊肉/茯茶）' },
  }),
  createGansuCounty({
    id: 'minqin', name: '民勤县', prefecture: '武威市', altitude: 1400,
    mapCoord: { x: 0.22, y: 0.35, elevation: 0.35 }, terrainArchetype: 'gobi',
    terrainType: '巴丹吉林与腾格里沙漠夹峙绿洲',
    terrainDescription: '两极沙漠在此交锋，红柳胡杨顽强锁住沙龙。',
    naturalLandmark: { name: '青土湖新生湿地与沙漠雕塑群', description: '瀚海重现碧波，芦苇万顷。', tag: '青土归碧' },
    culturalLandmark: { name: '瑞安堡地主庄园与沙井古遗存', description: '大漠深处的坚固军事民居。', tag: '大漠孤堡' },
    ethnicFeatures: { costumes: '治沙人风沙面纱防尘斗笠', crafts: '红柳编织筐具', traditions: '沙漠治沙压沙大会', specialty: '民勤蜜瓜、人参果' },
  }),
  createGansuCounty({
    id: 'gulang', name: '古浪县', prefecture: '武威市', altitude: 2070,
    mapCoord: { x: 0.18, y: 0.16, elevation: 0.46 }, terrainArchetype: 'loess',
    terrainType: '乌鞘岭高山分水岭隘口与八步沙黄沙',
    terrainDescription: '内陆河与外流河分水岭，扼控河西走廊东咽喉。',
    naturalLandmark: { name: '乌鞘岭主峰与八步沙林场', description: '山顶常年积雪，六老汉治沙奇迹。', tag: '乌鞘风雪' },
    culturalLandmark: { name: '昌松古峡与红军西路军烈士陵园', description: '古丝路第一要隘九曲险道。', tag: '古丝路隘口' },
    ethnicFeatures: { costumes: '高山抗寒羊皮马甲', crafts: '红柳草方格编织', traditions: '关隘烽燧守更', specialty: '古浪羊肉、八步沙枸杞' },
  }),
  createGansuCounty({
    id: 'tianzhu', name: '天祝藏族自治县', prefecture: '武威市', altitude: 2980,
    isAutonomous: true, ethnicGroup: '藏族',
    mapCoord: { x: 0.22, y: 0.10, elevation: 0.68 }, terrainArchetype: 'glacier',
    terrainType: '马牙雪山奇峰与金强川高山草甸',
    terrainDescription: '雪山利齿如马牙直刺蓝天，白牦牛在此繁衍，华藏圣境。',
    naturalLandmark: { name: '马牙雪山天池与冰川冰瀑', description: '万仞雪齿连绵，高山圣湖清澈见底。', tag: '马牙雪齿' },
    culturalLandmark: { name: '天堂寺千佛殿与木雕宗喀巴像', description: '祁连山南麓规模宏大的藏传佛教古刹。', tag: '天堂圣梵' },
    ethnicFeatures: { costumes: '厚重氆氇藏袍、白牦牛毛编织护腿', crafts: '白牦牛角工艺刻饰', traditions: '祝贡赛马节、转雪山', specialty: '天祝白牦牛肉、高山细毛羊' },
  }),

  // 7. 张掖市 (6)
  createGansuCounty({
    id: 'ganzhou', name: '甘州区', prefecture: '张掖市', altitude: 1480,
    mapCoord: { x: -0.10, y: 0.40, elevation: 0.38 }, terrainArchetype: 'meadow',
    terrainType: '黑河冲积塞上江南黑水绿洲',
    terrainDescription: '“不望祁连山顶雪，错将张掖认江南”，黑河滔滔润沃土。',
    naturalLandmark: { name: '张掖国家湿地公园', description: '内陆湿地，芦苇摇曳，天鹅戏水。', tag: '金张掖水乡' },
    culturalLandmark: { name: '张掖大佛寺（西夏皇家卧佛殿）', description: '亚洲最大的室内木胎泥塑卧佛。', tag: '西夏大卧佛' },
    ethnicFeatures: { costumes: '水乡汉式对襟绸缎袍', crafts: '甘州皮影与黑河麦秆画', traditions: '大佛寺浴佛庙会', specialty: '张掖牛肉小饭、搓鱼子' },
  }),
  createGansuCounty({
    id: 'sunan', name: '肃南裕固族自治县', prefecture: '张掖市', altitude: 2780,
    isAutonomous: true, ethnicGroup: '裕固族',
    mapCoord: { x: -0.15, y: 0.38, elevation: 0.65 }, terrainArchetype: 'glacier',
    terrainType: '祁连北麓冰川雪谷与高山天然草甸',
    terrainDescription: '终年积雪的峰峦与丰美的高山草场紧密相依，裕固古歌荡漾。',
    naturalLandmark: { name: '祁连山七一冰川', description: '极地冰川，冰层晶莹剔透，冰舌巍然横卧。', tag: '冰川奇观' },
    culturalLandmark: { name: '马蹄寺三十三天石窟群', description: '开凿于峭壁红岩上的千年佛窟。', tag: '绝壁古窟' },
    ethnicFeatures: { costumes: '裕固族红缨尖顶帽、大头面珊瑚项圈', crafts: '裕固皮雕贴花、织褐手工地毯', traditions: '祭鄂博神典、天鹅琴弹唱会', specialty: '高山黄菇羊肉、酥油奶茶' },
  }),
  createGansuCounty({
    id: 'minle', name: '民乐县', prefecture: '张掖市', altitude: 2270,
    mapCoord: { x: -0.05, y: 0.30, elevation: 0.52 }, terrainArchetype: 'canyon',
    terrainType: '扁都口险峡与万亩油菜花海金川',
    terrainDescription: '祁连山重要隘口，盛夏金色油菜花海漫向雪峰脚下。',
    naturalLandmark: { name: '扁都口油菜花大峡谷', description: '汉匈古道重关，金色锦缎铺满峡口。', tag: '丝路花峡' },
    culturalLandmark: { name: '永固城与霍去病古汉烽燧', description: '西汉骠骑将军饮马祁连古遗迹。', tag: '骠骑征尘' },
    ethnicFeatures: { costumes: '高山御寒棉布袍', crafts: '石桥古法压榨菜籽油', traditions: '扁都口花海歌会', specialty: '民乐苹果梨、扁都口菜籽油' },
  }),
  createGansuCounty({
    id: 'linze', name: '临泽县', prefecture: '张掖市', altitude: 1420,
    mapCoord: { x: -0.18, y: 0.44, elevation: 0.37 }, terrainArchetype: 'danxia',
    terrainType: '张掖七彩丹霞核心七彩丘陵',
    terrainDescription: '如上帝打翻的调色盘，红黄橙绿白交错起伏，光彩夺目。',
    naturalLandmark: { name: '张掖七彩丹霞国家地质公园', description: '色如渥丹，灿若明霞，世界级地貌奇观。', tag: '七彩丹霞' },
    culturalLandmark: { name: '香古寺与红军西路军烈士纪念馆', description: '丹霞峡谷内的清幽古寺。', tag: '丹霞古刹' },
    ethnicFeatures: { costumes: '枣农短衫围裙', crafts: '丹霞彩沙画瓶绘', traditions: '丹霞热气球节', specialty: '临泽小枣、小枣饴糖' },
  }),
  createGansuCounty({
    id: 'gaotai', name: '高台县', prefecture: '张掖市', altitude: 1350,
    mapCoord: { x: -0.24, y: 0.48, elevation: 0.35 }, terrainArchetype: 'meadow',
    terrainType: '黑河大湿地与戈壁黑泉绿洲',
    terrainDescription: '戈壁边缘的大片芦苇绿洲，候鸟迁徙重要驿站。',
    naturalLandmark: { name: '黑河黑泉大湿地保护区', description: '碧水回环，万鸟起落戈壁中。', tag: '戈壁候鸟家园' },
    culturalLandmark: { name: '骆驼城古城遗址', description: '汉唐丝绸之路保存最完整的古遗址之一。', tag: '西域重关' },
    ethnicFeatures: { costumes: '绿洲渔樵粗麻衣', crafts: '苇席柳编技艺', traditions: '湿地赛鸟会', specialty: '高台辣椒、黑番茄' },
  }),
  createGansuCounty({
    id: 'shandan', name: '山丹县', prefecture: '张掖市', altitude: 1760,
    mapCoord: { x: 0.00, y: 0.35, elevation: 0.44 }, terrainArchetype: 'meadow',
    terrainType: '山丹军马场无垠高山碧绿草原',
    terrainDescription: '霍去病始设的世界第一古老军马场，骏马奔腾雪山下。',
    naturalLandmark: { name: '山丹军马场与窟窿峡奇谷', description: '雪山环绕下的辽阔牧场，马群嘶鸣。', tag: '天下第一马场' },
    culturalLandmark: { name: '汉明双长城平行遗址', description: '汉长城与明长城首度平行共存奇景。', tag: '双长城奇绝' },
    ethnicFeatures: { costumes: '传统训马骑手皮靴皮裤', crafts: '山丹古法羊皮鞍辔', traditions: '祁连赛马节', specialty: '山丹炒拨拉、罐罐焖肉' },
  }),

  // 8. 平凉市 (7)
  createGansuCounty({
    id: 'kongtong', name: '崆峒区', prefecture: '平凉市', altitude: 1340,
    mapCoord: { x: 0.75, y: -0.02, elevation: 0.37 }, terrainArchetype: 'forest',
    terrainType: '崆峒道源奇险丹梯秀峰',
    terrainDescription: '道教第一名山，黄帝问道广成子处，奇峰耸峙。',
    naturalLandmark: { name: '崆峒山国家级风景名胜区', description: '峰林奇险，弹筝峡水环绕。', tag: '天下道教第一山' },
    culturalLandmark: { name: '崆峒山太统古刹道观群', description: '儒释道三教合一的玄天宫阁。', tag: '黄帝问道处' },
    ethnicFeatures: { costumes: '崆峒道长青玄袍、劲装武者服', crafts: '崆峒武术器械冷兵打制', traditions: '崆峒武术节', specialty: '平凉红牛、平凉金果' },
  }),
  createGansuCounty({
    id: 'jingchuan', name: '泾川县', prefecture: '平凉市', altitude: 1050,
    mapCoord: { x: 0.82, y: -0.02, elevation: 0.32 }, terrainArchetype: 'loess',
    terrainType: '泾河百里石窟绝壁走廊',
    terrainDescription: '泾河穿过红土与黄土交织河谷，佛窟鳞次栉比。',
    naturalLandmark: { name: '泾河河谷与王母宫天池', description: '翠峰环抱，回中山古道悠悠。', tag: '瑶池仙谷' },
    culturalLandmark: { name: '大云寺·王母宫石窟群', description: '出土佛祖真身舍利的唐代大云寺地宫。', tag: '佛门真身舍利' },
    ethnicFeatures: { costumes: '红土窑洞长袍', crafts: '平凉皮影与安国瓷刻', traditions: '西王母祖庙大祭', specialty: '泾川红富士苹果' },
  }),
  createGansuCounty({
    id: 'lingtai', name: '灵台县', prefecture: '平凉市', altitude: 1220,
    mapCoord: { x: 0.85, y: -0.08, elevation: 0.35 }, terrainArchetype: 'loess',
    terrainType: '古灵台针灸之乡黄土阶地',
    terrainDescription: '针灸鼻祖皇甫谧故里，地处陇东黄土塬腹地。',
    naturalLandmark: { name: '荆山森林公园与达溪河峡', description: '古松叠翠，深沟清泉。', tag: '荆山秀色' },
    culturalLandmark: { name: '文王伐密灵台古遗迹与皇甫谧纪念馆', description: '周文王筑台誓师之古灵台。', tag: '周礼古灵台' },
    ethnicFeatures: { costumes: '名医药农长衫', crafts: '传统银针古法打造', traditions: '祭医祖皇甫谧会', specialty: '灵台手工纯酸汤面' },
  }),
  createGansuCounty({
    id: 'chongxin', name: '崇信县', prefecture: '平凉市', altitude: 1180,
    mapCoord: { x: 0.80, y: -0.05, elevation: 0.34 }, terrainArchetype: 'forest',
    terrainType: '龙泉古寺悬崖飞瀑与古槐石林',
    terrainDescription: '汭河两岸林木葱茏，灵泉自古崖飞泻。',
    naturalLandmark: { name: '龙泉寺国家地质公园', description: '绝壁出甘泉，千年古槐缠绕飞阁。', tag: '龙泉飞瀑' },
    culturalLandmark: { name: '武康王李元谅神道碑', description: '唐代名将修筑崇信要塞功绩石刻。', tag: '盛唐名将碑' },
    ethnicFeatures: { costumes: '林泉居士素布袍', crafts: '古槐根雕手艺', traditions: '龙泉水龙会', specialty: '崇信红牛肉' },
  }),
  createGansuCounty({
    id: 'huating', name: '华亭市', prefecture: '平凉市', altitude: 1390,
    mapCoord: { x: 0.76, y: -0.09, elevation: 0.38 }, terrainArchetype: 'forest',
    terrainType: '关山林海连绵与煤陶矿谷',
    terrainDescription: '陇山东麓重镇，关山苍茫翠碧，煤瓷兼盛。',
    naturalLandmark: { name: '关山莲花台国家风景名胜区', description: '群峰形如莲花瓣，林海古木蔽日。', tag: '关山莲花' },
    culturalLandmark: { name: '安口古窑址（陇上瓷都）', description: '千年安口黑瓷与三彩古窑。', tag: '陇上瓷都' },
    ethnicFeatures: { costumes: '瓷工麻布套褂', crafts: '安口古法砂器烧制', traditions: '窑神香会', specialty: '华亭核桃、核桃包子' },
  }),
  createGansuCounty({
    id: 'zhuanglang', name: '庄浪县', prefecture: '平凉市', altitude: 1610,
    mapCoord: { x: 0.70, y: -0.07, elevation: 0.40 }, terrainArchetype: 'loess',
    terrainType: '天下第一梯田人工大地奇迹',
    terrainDescription: '全县百万亩黄土山峦全部改造成整齐台阶梯田。',
    naturalLandmark: { name: '中国梯田之乡百万亩大地阶梯', description: '如天梯层层盘旋至云霄的大地乐章。', tag: '大地天梯' },
    culturalLandmark: { name: '云崖寺石窟悬崖道观', description: '开凿于峭壁上的北魏佛窟，飞栈横空。', tag: '云崖石窟' },
    ethnicFeatures: { costumes: '梯田建设者布衣草鞋', crafts: '麦秆立体贴画', traditions: '梯田春耕大典', specialty: '庄浪粉条（马铃薯宽粉）' },
  }),
  createGansuCounty({
    id: 'jingning', name: '静宁县', prefecture: '平凉市', altitude: 1600,
    mapCoord: { x: 0.64, y: -0.06, elevation: 0.40 }, terrainArchetype: 'loess',
    terrainType: '葫芦河源黄土塬丘与金果山川',
    terrainDescription: '界连六盘山支脉，日照充足，苹果香飘四海。',
    naturalLandmark: { name: '界石铺高原烽台', description: '极目千里黄土塬梁，风云际会。', tag: '六盘古隘' },
    culturalLandmark: { name: '界石铺红军长征纪念馆', description: '毛泽东同志长征宿营古长廊。', tag: '长征宿营地' },
    ethnicFeatures: { costumes: '果农厚白粗布衫', crafts: '静宁剪纸窗花', traditions: '金果丰收节', specialty: '静宁烧鸡、静宁苹果' },
  }),

  // 9. 酒泉市 (7)
  createGansuCounty({
    id: 'suzhou_jq', name: '肃州区', prefecture: '酒泉市', altitude: 1470,
    mapCoord: { x: -0.38, y: 0.55, elevation: 0.38 }, terrainArchetype: 'gobi',
    terrainType: '酒泉西汉泉眼与祁连融雪绿洲',
    terrainDescription: '“霍去病倾御酒入泉与将士共饮”，酒泉得名之地。',
    naturalLandmark: { name: '酒泉西汉胜境飞泉', description: '碧泉喷涌，回廊古柳摇曳。', tag: '西汉金泉' },
    culturalLandmark: { name: '酒泉钟鼓楼与魏晋壁画墓', description: '中国古代地下画廊“驿使图”出土地。', tag: '天下第一鼓楼' },
    ethnicFeatures: { costumes: '汉代将士红披风配长衫', crafts: '酒泉夜光杯古法磨制（天然祁连玉）', traditions: '夜光杯玉宴', specialty: '夜光杯、酒泉糊锅' },
  }),
  createGansuCounty({
    id: 'yumen', name: '玉门市', prefecture: '酒泉市', altitude: 1520,
    mapCoord: { x: -0.48, y: 0.58, elevation: 0.39 }, terrainArchetype: 'gobi',
    terrainType: '玉门关故道与铁人第一石油河谷',
    terrainDescription: '祁连西麓大戈壁，风车如林，近代工业摇篮。',
    naturalLandmark: { name: '赤金峡水利风景区奇石峡', description: '黑山断崖切出的清凉河峡。', tag: '塞外小江南' },
    culturalLandmark: { name: '老君庙第一口油井旧址', description: '新中国石油工业发祥地。', tag: '铁人丰碑' },
    ethnicFeatures: { costumes: '坚韧耐磨蓝白工装', crafts: '戈壁奇石刻字', traditions: '铁人精神薪火传', specialty: '玉门人参果、戈壁羊肉' },
  }),
  createGansuCounty({
    id: 'dunhuang', name: '敦煌市', prefecture: '酒泉市', altitude: 1140,
    mapCoord: { x: -0.72, y: 0.62, elevation: 0.32 }, terrainArchetype: 'gobi',
    terrainType: '鸣沙山月牙泉瀚海沙漠绿洲',
    terrainDescription: '千百年来山泉共处沙水共生，丝路文明最璀璨明珠。',
    naturalLandmark: { name: '鸣沙山月牙泉天下第一奇景', description: '风夹金沙鸣如金鼓，月泉一弯清澈如月。', tag: '沙泉交响' },
    culturalLandmark: { name: '莫高窟千佛洞与玉门关遗址', description: '世界文化遗产，跨越千年的佛教壁画艺术殿堂。', tag: '东方莫高窟' },
    ethnicFeatures: { costumes: '莫高窟壁画飞天飘带与胡服', crafts: '敦煌彩塑古法矿物颜料调和技艺', traditions: '莫高窟乐舞、沙漠驼铃夜宴', specialty: '敦煌李广杏、驴肉黄面' },
  }),
  createGansuCounty({
    id: 'jinta', name: '金塔县', prefecture: '酒泉市', altitude: 1260,
    mapCoord: { x: -0.35, y: 0.65, elevation: 0.34 }, terrainArchetype: 'forest',
    terrainType: '金塔万亩金黄胡杨林水系湿地',
    terrainDescription: '深秋胡杨金波万顷，倒映在清澈水域中如梦似幻。',
    naturalLandmark: { name: '金塔沙漠胡杨林公园', description: '万亩金黄胡杨与湛蓝水面倒影交融。', tag: '瀚海金玉' },
    culturalLandmark: { name: '金塔古塔寺与大湾城古要塞', description: '汉代居延古道第一要津要塞。', tag: '汉家古塔' },
    ethnicFeatures: { costumes: '林中巡林者长袍', crafts: '胡杨木雕艺术', traditions: '胡杨金秋节', specialty: '金塔肉苁蓉、黑醋' },
  }),
  createGansuCounty({
    id: 'guazhou', name: '瓜州县', prefecture: '酒泉市', altitude: 1180,
    mapCoord: { x: -0.58, y: 0.60, elevation: 0.33 }, terrainArchetype: 'gobi',
    terrainType: '世界风库戈壁与锁阳城古要塞',
    terrainDescription: '狂风肆虐的大戈壁，古城墙与玄奘西行足迹长存。',
    naturalLandmark: { name: '戈壁清泉与大地之子雕塑群', description: '辽阔苍茫红戈壁上安睡的巨婴雕像。', tag: '大地之子' },
    culturalLandmark: { name: '锁阳城遗址与榆林窟石窟群', description: '玄奘西行受戒处，西夏壁画绝品之乡。', tag: '锁阳千年古城' },
    ethnicFeatures: { costumes: '大漠行僧粗麻衲衣', crafts: '锁阳天然切片精制', traditions: '玄奘西行徒步大会', specialty: '瓜州蜜瓜、锁阳' },
  }),
  createGansuCounty({
    id: 'subei', name: '肃北蒙古族自治县', prefecture: '酒泉市', altitude: 3050,
    isAutonomous: true, ethnicGroup: '蒙古族',
    mapCoord: { x: -0.65, y: 0.45, elevation: 0.70 }, terrainArchetype: 'glacier',
    terrainType: '党河南山极地透明梦柯冰川与雪山草原',
    terrainDescription: '雪山蒙古族世代游牧地，壮丽的极高山冰川奔泻而下。',
    naturalLandmark: { name: '透明梦柯二十九号大冰川', description: '祁连山最大山谷冰川，晶莹剔透似玉龙横卧。', tag: '透明梦柯' },
    culturalLandmark: { name: '五个庙石窟与党河大峡谷壁画', description: '崖壁上的古代藏传与蒙传佛教古迹。', tag: '雪山佛窟' },
    ethnicFeatures: { costumes: '雪山德都蒙袍、软帮起翘高统皮靴', crafts: '蒙古马鞍骨鞧手工制作', traditions: '雪山那达慕盛会、祭敖包', specialty: '肃北风干牦牛肉、奶豆腐' },
  }),
  createGansuCounty({
    id: 'akesai', name: '阿克塞哈萨克族自治县', prefecture: '酒泉市', altitude: 2800,
    isAutonomous: true, ethnicGroup: '哈萨克族',
    mapCoord: { x: -0.78, y: 0.48, elevation: 0.66 }, terrainArchetype: 'gobi',
    terrainType: '阿尔金山北坡苏干湖候鸟湿地与戈壁荒原',
    terrainDescription: '大柴旦往北越过当金山口，金鹰展翅傲视瀚海盐湖。',
    naturalLandmark: { name: '大苏干湖与小苏干湖湿地', description: '沙漠深处纯净碧蓝的候鸟天堂。', tag: '高原双碧湖' },
    culturalLandmark: { name: '博罗转井影视古镇', description: '老县城遗址保留着沧桑的八十年代建筑风貌。', tag: '老县城秘境' },
    ethnicFeatures: { costumes: '白狐皮尖顶帽（绍克列）、刺绣羊角纹开襟长袍', crafts: '哈萨克金鹰驯养器具手工缝皮', traditions: '“姑娘追”马上竞技、冬不拉弹唱会', specialty: '哈萨克马奶酒、包尔萨克' },
  }),

  // 10. 庆阳市 (8)
  createGansuCounty({
    id: 'xifeng', name: '西峰区', prefecture: '庆阳市', altitude: 1350,
    mapCoord: { x: 0.88, y: 0.08, elevation: 0.36 }, terrainArchetype: 'loess',
    terrainType: '天下第一大塬董志塬核心原心',
    terrainDescription: '世界上黄土层最深厚、面积最广阔的雄奇大塬。',
    naturalLandmark: { name: '董志塬黄土大冲沟天险', description: '刀削般的黄土绝壁展露千万年地层历史。', tag: '天下第一塬' },
    culturalLandmark: { name: '北石窟寺唐代造像群', description: '开凿于黄土峡壁上的莫高窟姊妹窟。', tag: '北石窟宝藏' },
    ethnicFeatures: { costumes: '庆阳红绿民俗刺绣围兜', crafts: '庆阳香包绣制（国家级非遗）', traditions: '庆阳香包民俗节', specialty: '庆阳苹果、黄米稠饭' },
  }),
  createGansuCounty({
    id: 'qingcheng', name: '庆城县', prefecture: '庆阳市', altitude: 1100,
    mapCoord: { x: 0.89, y: 0.15, elevation: 0.33 }, terrainArchetype: 'loess',
    terrainType: '周祖农耕发祥地环江两岸古塬',
    terrainDescription: '周先祖不窋教民稼穑之地，环江与柔远河环抱凤城。',
    naturalLandmark: { name: '鹅池春涨与翠屏叠翠', description: '双河汇聚，青峦古亭相照。', tag: '凤城双碧' },
    culturalLandmark: { name: '周祖陵国家森林公园与岐黄中医药博览馆', description: '华夏农耕文明第一陵。', tag: '周祖圣陵' },
    ethnicFeatures: { costumes: '上古农耕麻葛深衣', crafts: '陇东窑洞窗花剪纸', traditions: '祭周祖稼穑大典', specialty: '庆城黄酒、普照寺豆腐' },
  }),
  createGansuCounty({
    id: 'huanxian', name: '环县', prefecture: '庆阳市', altitude: 1380,
    mapCoord: { x: 0.78, y: 0.28, elevation: 0.37 }, terrainArchetype: 'loess',
    terrainType: '环江两岸黄土旱谷与长城秦砖烽燧',
    terrainDescription: '地扼陕甘宁交界要冲，皮影戏曲声震长夜。',
    naturalLandmark: { name: '八珠翠屏山', description: '黄土旱原上的翠绿明珠。', tag: '八珠屏障' },
    culturalLandmark: { name: '环县宋代砖塔与中国皮影博物馆', description: '世界皮影之乡，高耸密檐古塔。', tag: '中国皮影之乡' },
    ethnicFeatures: { costumes: '皮影戏班唱腔道袍', crafts: '环县道情皮影手工牛皮镂刻', traditions: '道情皮影彻夜大戏', specialty: '环县羊羔肉（国家地理标志）' },
  }),
  createGansuCounty({
    id: 'huachi', name: '华池县', prefecture: '庆阳市', altitude: 1280,
    mapCoord: { x: 0.90, y: 0.22, elevation: 0.35 }, terrainArchetype: 'forest',
    terrainType: '子午岭原始古松森林大峡谷',
    terrainDescription: '陕甘边界绿色屏障，古秦直道穿岭而过。',
    naturalLandmark: { name: '子午岭国家级自然保护区', description: '高大油松漫山遍野，野生金钱豹栖息地。', tag: '子午林海' },
    culturalLandmark: { name: '南梁革命纪念馆与大凤川军民大生产旧址', description: '陕甘边苏维埃政府诞生地。', tag: '陕甘红都南梁' },
    ethnicFeatures: { costumes: '陕甘红军八角帽与布行装', crafts: '松木古法炭刻', traditions: '南梁红歌会', specialty: '华池黄粮米、小磨香油' },
  }),
  createGansuCounty({
    id: 'heshui', name: '合水县', prefecture: '庆阳市', altitude: 1200,
    mapCoord: { x: 0.93, y: 0.16, elevation: 0.34 }, terrainArchetype: 'forest',
    terrainType: '古黄河古象发掘地古道林泉',
    terrainDescription: '出土世界闻名的黄河剑齿象化石，林丰泉甘。',
    naturalLandmark: { name: '子午岭太白森林深谷', description: '清泉石上流，古林遮天日。', tag: '太白松风' },
    culturalLandmark: { name: '黄河象古化石发现地与保宁寺石塔', description: '三百万年前黄河象骨架出土遗址。', tag: '黄河古象故里' },
    ethnicFeatures: { costumes: '林农厚毡布袄', crafts: '象牙石泥塑仿制', traditions: '陇东道情班会', specialty: '合水金丝黄花菜' },
  }),
  createGansuCounty({
    id: 'zhengning', name: '正宁县', prefecture: '庆阳市', altitude: 1150,
    mapCoord: { x: 0.92, y: 0.02, elevation: 0.33 }, terrainArchetype: 'forest',
    terrainType: '子午岭南麓百里林海与三嘉峡谷',
    terrainDescription: '地接陕西旬邑，林海茂密，盛产名果。',
    naturalLandmark: { name: '调令关秦直道森林关口', description: '秦始皇修筑天下第一高速公路关隘。', tag: '秦直道第一关' },
    culturalLandmark: { name: '罗川赵氏石坊群', description: '明代精美绝伦的明代功德石雕牌楼。', tag: '罗川明坊' },
    ethnicFeatures: { costumes: '秦陇交界青布深褂', crafts: '民间泥偶吹叫叫', traditions: '直道马帮集市', specialty: '正宁苹果、正宁豆腐干' },
  }),
  createGansuCounty({
    id: 'ningxian', name: '宁县', prefecture: '庆阳市', altitude: 1120,
    mapCoord: { x: 0.88, y: 0.05, elevation: 0.32 }, terrainArchetype: 'loess',
    terrainType: '九龙川河谷盆地与黄土高台',
    terrainDescription: '古称宁州，九龙川交汇处，古墓葬遗址遍布。',
    naturalLandmark: { name: '九龙金川与政平红层峡谷', description: '水绕青山，红土岩壁在河岸铺开。', tag: '九龙灵秀' },
    culturalLandmark: { name: '石空寺石窟与王孝锡烈士陵园', description: '宋代摩崖古佛雕刻群。', tag: '石空古窟' },
    ethnicFeatures: { costumes: '传统关中风韵盘扣黑棉袍', crafts: '金石拓印与红土泥哨', traditions: '宁县皮影高腔', specialty: '宁县早胜牛肉（黄牛极品）' },
  }),
  createGansuCounty({
    id: 'zhenyuan', name: '镇原县', prefecture: '庆阳市', altitude: 1320,
    mapCoord: { x: 0.82, y: 0.10, elevation: 0.36 }, terrainArchetype: 'loess',
    terrainType: '茹河深切大峡谷与北武当石峰',
    terrainDescription: '茹河奔腾如切巨石，丹崖与黄土相间。',
    naturalLandmark: { name: '潜夫山森林公园与茹河瀑布', description: '山峰挺秀，东汉王符潜隐地。', tag: '潜夫幽境' },
    culturalLandmark: { name: '原州古城与北武当玄帝庙', description: '北魏丝路重镇要塞堡垒。', tag: '北武当古刹' },
    ethnicFeatures: { costumes: '陇东书生深蓝麻袍', crafts: '镇原书画装裱古法技艺', traditions: '中国民间书法之乡大擂台', specialty: '镇原杏仁油、荞麦糁子' },
  }),

  // 11. 定西市 (7)
  createGansuCounty({
    id: 'anding', name: '安定区', prefecture: '定西市', altitude: 1900,
    mapCoord: { x: 0.46, y: -0.09, elevation: 0.44 }, terrainArchetype: 'loess',
    terrainType: '“苦瘠甲天下”变身马铃薯花海梯田',
    terrainDescription: '黄土高原典型的干旱梁峁，如今万顷土豆花如星海。',
    naturalLandmark: { name: '西岩山神秀峰', description: '俯瞰定西全城，晚钟悠悠。', tag: '西岩晚钟' },
    culturalLandmark: { name: '定西中国马铃薯博物馆', description: '记录从苦瘠黄土到“中国薯都”的涅槃史。', tag: '中国薯都之核' },
    ethnicFeatures: { costumes: '耐旱棉麻灰布对襟老衣', crafts: '定西麦秆编结手艺', traditions: '马铃薯花海丰收节', specialty: '定西马铃薯、宽粉定西烩菜' },
  }),
  createGansuCounty({
    id: 'tongwei', name: '通渭县', prefecture: '定西市', altitude: 1730,
    mapCoord: { x: 0.54, y: -0.12, elevation: 0.42 }, terrainArchetype: 'loess',
    terrainType: '牛谷河畔神泉温汤与中国书画名乡',
    terrainDescription: '“家中无字画，不是通渭人”，黄土深处书香满城。',
    naturalLandmark: { name: '通渭高温泉水森林公园', description: '天然高热矿泉，神汤洗凝脂。', tag: '陇上神泉' },
    culturalLandmark: { name: '榜罗镇会议旧址', description: '红军长征决定落脚陕北的关键会议地。', tag: '榜罗定乾坤' },
    ethnicFeatures: { costumes: '墨香沾襟的文人棉衫', crafts: '通渭书画宣纸精裱与拓片', traditions: '通渭全城书画交易大集', specialty: '通渭荞圈圈、通渭甜醅子' },
  }),
  createGansuCounty({
    id: 'longxi', name: '陇西县', prefecture: '定西市', altitude: 1650,
    mapCoord: { x: 0.50, y: -0.15, elevation: 0.40 }, terrainArchetype: 'loess',
    terrainType: '渭水之滨天下李氏祖宗圣地',
    terrainDescription: '渭水穿流，渭水台地上屹立威远古钟楼。',
    naturalLandmark: { name: '仁寿山森林胜景', description: '山形如佛卧，古木参天。', tag: '仁寿胜概' },
    culturalLandmark: { name: '李家龙宫与威远楼', description: '全球李氏宗亲寻根祭祖总祠。', tag: '天下第一李家龙宫' },
    ethnicFeatures: { costumes: '盛唐李唐宗族华美汉服', crafts: '黄芪白芍切片古法炮制', traditions: '李氏祭祖大典、药交会', specialty: '陇西腊肉、陇西白条党参' },
  }),
  createGansuCounty({
    id: 'lintao', name: '临洮县', prefecture: '定西市', altitude: 1640,
    mapCoord: { x: 0.39, y: -0.10, elevation: 0.39 }, terrainArchetype: 'loess',
    terrainType: '洮河大冲积平原与马家窑文化源头',
    terrainDescription: '洮河蜿蜒，两岸台地埋藏五千年新石器彩陶绝品。',
    naturalLandmark: { name: '岳麓山古叠秀峰', description: '洮水绕其足，琴台迎晚风。', tag: '岳麓晚照' },
    culturalLandmark: { name: '马家窑遗址与秦长城西起首标志', description: '秦万里长城真正西端起点在此。', tag: '秦长城之首' },
    ethnicFeatures: { costumes: '战国秦风戎装与汉袍', crafts: '彩陶双耳罐纯手工拉坯', traditions: '洮河花儿对唱会', specialty: '临洮热牛肉、临洮花木牡丹' },
  }),
  createGansuCounty({
    id: 'weiyuan', name: '渭源县', prefecture: '定西市', altitude: 2080,
    mapCoord: { x: 0.45, y: -0.16, elevation: 0.47 }, terrainArchetype: 'forest',
    terrainType: '华夏母亲河渭水鸟鼠山大源头',
    terrainDescription: '大禹导渭于此，高山深谷中云杉漫布，甘泉喷涌。',
    naturalLandmark: { name: '鸟鼠山大禹导渭源头', description: '“鸟鼠同穴”奇观，三眼清泉奔腾成八百里渭河。', tag: '源出鸟鼠' },
    culturalLandmark: { name: '灞陵纯木悬臂古拱桥', description: '中国第一座纯木无柱悬臂卧桥，巧夺天工。', tag: '天下第一灞陵桥' },
    ethnicFeatures: { costumes: '药农羊皮坎肩', crafts: '渭源白条党参古法扎把', traditions: '祭禹王水典', specialty: '渭源白条党参、高山黄芪' },
  }),
  createGansuCounty({
    id: 'zhangxian', name: '漳县', prefecture: '定西市', altitude: 1720,
    mapCoord: { x: 0.52, y: -0.22, elevation: 0.42 }, terrainArchetype: 'canyon',
    terrainType: '贵清山丹崖峡谷与遮阳山鬼斧神工',
    terrainDescription: '陇上小九寨，悬崖千丈，古藤缠绕，溪流穿石。',
    naturalLandmark: { name: '贵清山顶断头崖与遮阳山绝壁一线天', description: '仙人峰奇拔挺秀，飞瀑直下三千尺。', tag: '陇中九寨' },
    culturalLandmark: { name: '汪氏元代世袭家族墓群', description: '元代陇右巨族汪世显庞大地下宫殿。', tag: '元代汪氏古陵' },
    ethnicFeatures: { costumes: '林区猎户劲装马裤', crafts: '高山沙棘原浆石磨压制', traditions: '朝贵清山神庙会', specialty: '漳县蚕豆、高山沙棘' },
  }),
  createGansuCounty({
    id: 'minxian', name: '岷县', prefecture: '定西市', altitude: 2310,
    mapCoord: { x: 0.47, y: -0.25, elevation: 0.53 }, terrainArchetype: 'meadow',
    terrainType: '中国当归之乡洮河谷地与高寒草场',
    terrainDescription: '高寒阴湿润泽万千草药，当归药香浸透山川。',
    naturalLandmark: { name: '狼渡湿地草原万亩水草', description: '九曲狼渡溪流在草原上蜿蜒如龙。', tag: '狼渡云甸' },
    culturalLandmark: { name: '二郎山花儿台与岷州古卫城', description: '河州西北花儿民歌盛典之山。', tag: '花儿之海' },
    ethnicFeatures: { costumes: '药农防寒布袍配宽腰带', crafts: '岷县“岷归”道地炮制技艺', traditions: '二郎山六月六花儿盛会', specialty: '岷县当归（中华当归之冠）、点点点点心' },
  }),

  // 12. 陇南市 (9)
  createGansuCounty({
    id: 'wudu', name: '武都区', prefecture: '陇南市', altitude: 1080,
    mapCoord: { x: 0.56, y: -0.38, elevation: 0.32 }, terrainArchetype: 'canyon',
    terrainType: '白龙江深切大峡谷与中国橄榄之都',
    terrainDescription: '亚热带气候润泽，江水滔滔，两岸万顷油橄榄青翠。',
    naturalLandmark: { name: '万象洞地下溶洞宫殿', description: '华夏北方最大天然钟乳石溶洞，奇幻万千。', tag: '华夏第一洞' },
    culturalLandmark: { name: '仇池国古遗迹与朝阳洞古刹', description: '南北朝氐杨割据仇池国险峻石堡。', tag: '仇池古国' },
    ethnicFeatures: { costumes: '陇南古氐羌蓝花短衣', crafts: '武都橄榄油冷榨技艺', traditions: '万象洞朝仙节', specialty: '武都大红袍花椒、特级橄榄油' },
  }),
  createGansuCounty({
    id: 'chengxian', name: '成县', prefecture: '陇南市', altitude: 1000,
    mapCoord: { x: 0.64, y: -0.32, elevation: 0.30 }, terrainArchetype: 'forest',
    terrainType: '西狭飞瀑摩崖汉阙翠绿小江南',
    terrainDescription: '峰峦翠绿，飞泉流瀑，唐代诗圣杜甫留居之处。',
    naturalLandmark: { name: '鸡峰山国家森林公园与西狭流瀑', description: '峰如鸡冠耸立，飞泉喷涌若素练。', tag: '鸡峰耸秀' },
    culturalLandmark: { name: '西狭颂汉代摩崖石刻（惠安西表）', description: '汉隶书法神品，刻于悬崖峭壁千年不损。', tag: '西狭汉隶第一碑' },
    ethnicFeatures: { costumes: '江南温润青布袍', crafts: '成县传统雕版拓石', traditions: '杜甫草堂诗会', specialty: '成县核桃、土蜂蜜' },
  }),
  createGansuCounty({
    id: 'wenxian', name: '文县', prefecture: '陇南市', altitude: 950,
    mapCoord: { x: 0.52, y: -0.48, elevation: 0.28 }, terrainArchetype: 'forest',
    terrainType: '白马藏族古寨与碧口茶乡碧波天池',
    terrainDescription: '白水江奔腾南下，大熊猫栖息地，气候如巴蜀湿润。',
    naturalLandmark: { name: '文县天池国家级自然保护区', description: '中国四大天池之一，九道大湾水深如海。', tag: '天池神玉' },
    culturalLandmark: { name: '白马藏族草河古寨与池哥昼面具', description: '头戴白鸟羽毡帽的古老氐族后裔。', tag: '白马古氐' },
    ethnicFeatures: { costumes: '头插白色公鸡尾羽的毡帽、彩锦连衫袍', crafts: '白马藏族“池哥昼”古木面具雕刻', traditions: '跳“池哥昼”驱邪祈福大典', specialty: '碧口龙神翠峰绿茶、文县纹党参' },
  }),
  createGansuCounty({
    id: 'dangchang', name: '宕昌县', prefecture: '陇南市', altitude: 1820,
    mapCoord: { x: 0.49, y: -0.28, elevation: 0.45 }, terrainArchetype: 'canyon',
    terrainType: '官鹅沟神奇瀑布峡谷与冰瀑圣境',
    terrainDescription: '小九寨之美，十三道高山湖泊连接二十处连绵飞瀑。',
    naturalLandmark: { name: '官鹅沟国家5A级风景区与通天门瀑布', description: '两山对峙仅数米，瀑布自云端飞下。', tag: '官鹅叠瀑' },
    culturalLandmark: { name: '哈达铺红军长征纪念馆与古街', description: '“红军长征的加油站”，在此决定进军陕北。', tag: '红军加油站' },
    ethnicFeatures: { costumes: '木制鹿角头饰与藏羌锦绣长裙', crafts: '官鹅竹筒酒酿制', traditions: '官鹅沟转山踏泉节', specialty: '哈达铺锅盔、宕昌党参' },
  }),
  createGansuCounty({
    id: 'kangxian', name: '康县', prefecture: '陇南市', altitude: 1100,
    mapCoord: { x: 0.68, y: -0.38, elevation: 0.33 }, terrainArchetype: 'forest',
    terrainType: '阳坝亚热带生态茶海与梅园古沟',
    terrainDescription: '陇上唯一的亚热带原始密林，红豆杉漫山遍野。',
    naturalLandmark: { name: '阳坝梅园沟国家级生态旅游区', description: '万亩茶海，青翠欲滴，奇花异兽。', tag: '陇上西双版纳' },
    culturalLandmark: { name: '康县花桥美丽乡村与白马关', description: '茶马古道川陕甘交汇重关。', tag: '茶马古道津' },
    ethnicFeatures: { costumes: '茶农轻便采茶服', crafts: '红豆杉木雕与手工竹篾编茶篓', traditions: '采茶歌节', specialty: '康县龙神毛尖、黑木耳' },
  }),
  createGansuCounty({
    id: 'xihe', name: '西和县', prefecture: '陇南市', altitude: 1400,
    mapCoord: { x: 0.60, y: -0.26, elevation: 0.38 }, terrainArchetype: 'loess',
    terrainType: '中国乞巧文化之乡秀美仇池山',
    terrainDescription: '相传为仇池国核心地带，保留最完整的千年乞巧古礼。',
    naturalLandmark: { name: '仇池石山奇拔孤峰', description: '四壁皆绝，山顶平坦万亩，天险天成。', tag: '仇池神垒' },
    culturalLandmark: { name: '西和乞巧节圣坛与岷郡古遗', description: '全国独一无二延续七天八夜的女儿乞巧盛典。', tag: '中国乞巧之乡' },
    ethnicFeatures: { costumes: '乞巧织女素白云锦长裙', crafts: '西和麻柳刺绣与巧娘面花', traditions: '七夕“迎巧、拜巧、唱巧、送巧”大礼', specialty: '西和锅盔、西和八宝洋芋搅团' },
  }),
  createGansuCounty({
    id: 'lixian', name: '礼县', prefecture: '陇南市', altitude: 1520,
    mapCoord: { x: 0.56, y: -0.24, elevation: 0.40 }, terrainArchetype: 'loess',
    terrainType: '秦人发祥地大堡子山秦皇第一陵',
    terrainDescription: '西汉水上游西犬丘，大秦帝国六百年雄图策源地。',
    naturalLandmark: { name: '祁山武侯祠千仞绝壁', description: '诸葛亮六出祁山前线大营。', tag: '诸葛六出祁山' },
    culturalLandmark: { name: '大堡子山秦第一代国君先祖陵园', description: '出土珍贵秦子镈与金铠甲片。', tag: '大秦肇基之陵' },
    ethnicFeatures: { costumes: '大秦黑金军甲与铁血战袍', crafts: '青铜金兽面纹失蜡浇铸技艺', traditions: '祭祀秦穆公与武侯祠八卦阵会', specialty: '礼县大红富士苹果、当归' },
  }),
  createGansuCounty({
    id: 'huixian', name: '徽县', prefecture: '陇南市', altitude: 1020,
    mapCoord: { x: 0.66, y: -0.28, elevation: 0.31 }, terrainArchetype: 'forest',
    terrainType: '嘉陵江源头两当峡与青泥古道',
    terrainDescription: '“百步九折萦岩峦”，李白《蜀道难》叹青泥之险。',
    naturalLandmark: { name: '三滩国家森林公园飞瀑碧潭', description: '碧潭如玉，林海茫茫，小江南风光。', tag: '三滩奇瀑' },
    culturalLandmark: { name: '青泥岭蜀道遗迹与仙人关金代大捷旧址', description: '吴玠吴璘阻击金兀术大军雄关。', tag: '仙人关金戈' },
    ethnicFeatures: { costumes: '蜀道挑夫布衫麻鞋', crafts: '徽县古法金徽酒五粮泥池酿造', traditions: '仙人关武圣祭会', specialty: '金徽大曲酒、徽县银杏' },
  }),
  createGansuCounty({
    id: 'liangdang', name: '两当县', prefecture: '陇南市', altitude: 1050,
    mapCoord: { x: 0.72, y: -0.25, elevation: 0.32 }, terrainArchetype: 'forest',
    terrainType: '广金红叶峡谷与云屏三里石门',
    terrainDescription: '秦岭南麓深山，红叶似火，深涧幽潭相连。',
    naturalLandmark: { name: '云屏三里峡一线天与幽谷石林', description: '绝壁夹峙，清溪绕石。', tag: '云屏三里' },
    culturalLandmark: { name: '两当兵变旧址与张果老登真洞', description: '习仲勋同志领导的两当起义圣地。', tag: '两当起义星火' },
    ethnicFeatures: { costumes: '老八路灰布军衣', crafts: '野生狼牙蜜古法割糖', traditions: '红叶节歌咏会', specialty: '两当狼牙蜜、土猪老腊肉' },
  }),

  // 13. 临夏回族自治州 (8)
  createGansuCounty({
    id: 'linxia_shi', name: '临夏市', prefecture: '临夏回族自治州', altitude: 1910,
    ethnicGroup: '回族',
    mapCoord: { x: 0.30, y: -0.06, elevation: 0.42 }, terrainArchetype: 'canyon',
    terrainType: '大夏河畔八坊十三巷河州明珠',
    terrainDescription: '西北穆斯林风情之都，砖雕木雕精美绝伦。',
    naturalLandmark: { name: '大夏河碧流与红水河峡', description: '雪山融水蜿蜒如玉带穿城。', tag: '大夏清流' },
    culturalLandmark: { name: '八坊十三巷与东公馆国家级砖雕', description: '全国最具代表性的砖雕艺术院落。', tag: '河州砖雕之都' },
    ethnicFeatures: { costumes: '素白平顶回帽、手工刺绣盖头', crafts: '国家级非遗【临夏砖雕】（圆雕/浮雕/透雕绝技）', traditions: '松鸣岩花儿会、盖碗茶茶道', specialty: '河州盖碗八宝茶、河州酿皮' },
  }),
  createGansuCounty({
    id: 'linxia_xian', name: '临夏县', prefecture: '临夏回族自治州', altitude: 2000,
    mapCoord: { x: 0.28, y: -0.08, elevation: 0.43 }, terrainArchetype: 'meadow',
    terrainType: '太子山终年积雪雪峰草场',
    terrainDescription: '太子山如巍峨银屏耸立，山脚草原繁花似锦。',
    naturalLandmark: { name: '太子山主峰与双咀石奇峡', description: '山顶白雪皑皑，山谷松涛林海。', tag: '太子雪屏' },
    culturalLandmark: { name: '解放军抢渡黄河旧址与红台遗址', description: '红军与解放大军西进关键渡口。', tag: '大河红魂' },
    ethnicFeatures: { costumes: '花儿歌手蓝布长袍', crafts: '骨雕花儿三弦琴制法', traditions: '太子山浪山节', specialty: '临夏县黄蒸、爆炒草鸡' },
  }),
  createGansuCounty({
    id: 'kangle', name: '康乐县', prefecture: '临夏回族自治州', altitude: 2050,
    mapCoord: { x: 0.35, y: -0.12, elevation: 0.45 }, terrainArchetype: 'forest',
    terrainType: '松鸣岩高山松涛与药水峡飞瀑',
    terrainDescription: '松涛声鸣动峡谷，名列西北花儿第一盛会之所。',
    naturalLandmark: { name: '松鸣岩国家级森林公园与药水峡', description: '奇峰出云，古松参天，泉水可愈疾。', tag: '松鸣松涛' },
    culturalLandmark: { name: '松鸣岩花儿古戏台与菩萨大殿', description: '数万人对唱花儿山歌的西北民歌圣地。', tag: '西北花儿第一台' },
    ethnicFeatures: { costumes: '花儿手绢配大襟花袄', crafts: '古法木簧与铜锣铸造', traditions: '四月二十八松鸣岩花儿大盛会', specialty: '康乐高原食用菌、菜籽油' },
  }),
  createGansuCounty({
    id: 'yongjing', name: '永靖县', prefecture: '临夏回族自治州', altitude: 1650,
    mapCoord: { x: 0.31, y: -0.02, elevation: 0.39 }, terrainArchetype: 'danxia',
    terrainType: '炳灵寺千佛红崖与刘家峡高峡平湖',
    terrainDescription: '黄河在此清澈碧绿，赤壁丹霞与石窟倒映万顷碧波。',
    naturalLandmark: { name: '黄河三峡（炳灵峡/刘家峡/盐锅峡）', description: '“天下黄河贵德清，刘家峡里水碧清”。', tag: '天下第一清黄河' },
    culturalLandmark: { name: '炳灵寺石窟世界文化遗产', description: '开凿于西秦建弘元年的悬崖巨大弥勒佛。', tag: '炳灵石窟大佛' },
    ethnicFeatures: { costumes: '大禹后人水手短褂', crafts: '恐龙足迹微缩石拓', traditions: '黄河龙舟竞渡', specialty: '刘家峡金鳟红鳟冷水鱼、白兰瓜' },
  }),
  createGansuCounty({
    id: 'guanghe', name: '广河县', prefecture: '临夏回族自治州', altitude: 1950,
    mapCoord: { x: 0.34, y: -0.07, elevation: 0.43 }, terrainArchetype: 'loess',
    terrainType: '广通河冲积谷地齐家文化故里',
    terrainDescription: '中国早期青铜文明齐家文化的起源核心地带。',
    naturalLandmark: { name: '太子山延伸梁峁与广通河湿地', description: '河滩绿水环绕，黄土崖壁藏玉璋。', tag: '广通河脉' },
    culturalLandmark: { name: '齐家文化博物馆与齐家坪遗址', description: '中华玉礼器与青铜镜最初起源圣地。', tag: '齐家文明源' },
    ethnicFeatures: { costumes: '皮毛客商人坎肩', crafts: '齐家古玉石器仿磨与羊皮毛鞣制', traditions: '皮毛交易商会大集', specialty: '广河甜醅、皮毛手抓' },
  }),
  createGansuCounty({
    id: 'hezheng', name: '和政县', prefecture: '临夏回族自治州', altitude: 2200,
    mapCoord: { x: 0.32, y: -0.10, elevation: 0.47 }, terrainArchetype: 'forest',
    terrainType: '世界古动物化石之都与松鸣松峦',
    terrainDescription: '青藏高原隆升的活化石记录，三趾马与铲齿象古故乡。',
    naturalLandmark: { name: '铁沟古生态林与三岔沟瀑布', description: '幽谷险峻，古木森森。', tag: '铁沟清凉' },
    culturalLandmark: { name: '和政古动物化石博物馆（六项世界之最）', description: '拥有世界最大的三趾马动物群与巨顶鬣狗化石。', tag: '东方古化石宝库' },
    ethnicFeatures: { costumes: '高山护林人粗皮护腕', crafts: '古生物化石科学复原打磨技艺', traditions: '花儿采风节', specialty: '和政啤特果（高原解酒圣果）' },
  }),
  createGansuCounty({
    id: 'dongxiang', name: '东乡族自治县', prefecture: '临夏回族自治州', altitude: 2150,
    isAutonomous: true, ethnicGroup: '东乡族',
    mapCoord: { x: 0.28, y: -0.05, elevation: 0.45 }, terrainArchetype: 'danxia',
    terrainType: '黄土高原千沟万壑与红层丹霞梁峁',
    terrainDescription: '群山连绵、沟壑纵横，布楞沟红石与黄土相间壮怀激烈。',
    naturalLandmark: { name: '布楞沟丹霞大峡谷', description: '黄土与赭红丹霞交织，如巨龙盘踞旱塬。', tag: '丹霞深壑' },
    culturalLandmark: { name: '东乡族擀毡技艺传习所与民居', description: '国家级非物质文化遗产【东乡擀毡】。', tag: '纯羊毛手工擀毡' },
    ethnicFeatures: { costumes: '素黑素白无檐平帽、青绿丝质盖头', crafts: '国家级非遗【东乡擀毡技艺】、东乡刺绣', traditions: '东乡花儿、折羊宴传统婚典', specialty: '天下闻名东乡手抓羊肉、油馓子' },
  }),
  createGansuCounty({
    id: 'jishishan', name: '积石山保安族东乡族撒拉族自治县', prefecture: '临夏回族自治州', altitude: 2350,
    isAutonomous: true, ethnicGroup: '保安族',
    mapCoord: { x: 0.24, y: -0.06, elevation: 0.50 }, terrainArchetype: 'canyon',
    terrainType: '积石雄关大峡谷与黄河险滩渡口',
    terrainDescription: '大禹治水“导河自积石”，大河奔腾，群峰巍峨。',
    naturalLandmark: { name: '积石雄关与大河家黄河第一湾', description: '奇石嶙峋，黄河自青海峡谷咆哮而出。', tag: '积石神关' },
    culturalLandmark: { name: '保安腰刀大河家制作技艺传承基地', description: '国家级非物质文化遗产【保安腰刀制作技艺】。', tag: '削铁如泥名刀' },
    ethnicFeatures: { costumes: '头戴白礼帽、对襟黑坎肩，腰佩保安腰刀', crafts: '保安腰刀锻造技艺（经40余道淬火工序，削铁如泥）', traditions: '保安宴席曲、克雷宴', specialty: '积石山大红袍花椒、保安风干肉' },
  }),

  // 14. 甘南藏族自治州 (8)
  createGansuCounty({
    id: 'hezuo', name: '合作市', prefecture: '甘南藏族自治州', altitude: 2960,
    ethnicGroup: '藏族',
    mapCoord: { x: 0.29, y: -0.18, elevation: 0.62 }, terrainArchetype: 'meadow',
    terrainType: '当周高山天然草甸草原与米拉日巴圣阁',
    terrainDescription: '甘南首府羚城，绿毯铺向雪峰，九层佛阁耸入蓝天。',
    naturalLandmark: { name: '当周草原高山天然草甸', description: '万亩碧草，牛羊如珍珠撒落。', tag: '羚城碧草' },
    culturalLandmark: { name: '米拉日巴九层佛阁', description: '藏区唯一的九层佛阁，供奉各教派祖师。', tag: '九层米拉日巴佛阁' },
    ethnicFeatures: { costumes: '华美红黄缎带氆氇藏袍、珊瑚玛瑙腰扣', crafts: '金铜佛像手工鎏金錾刻', traditions: '羚城香浪节、毛兰姆祈愿大法会', specialty: '甘南牦牛奶酪、手抓羊肉' },
  }),
  createGansuCounty({
    id: 'lintan', name: '临潭县', prefecture: '甘南藏族自治州', altitude: 2820,
    ethnicGroup: '藏族',
    mapCoord: { x: 0.38, y: -0.18, elevation: 0.58 }, terrainArchetype: 'meadow',
    terrainType: '冶力关天池神山与天池飞瀑草原',
    terrainDescription: '冶木河滔滔穿行峡谷，巨型卧佛在天际线横卧。',
    naturalLandmark: { name: '冶力关国家级风景区（十里卧佛天际奇观）', description: '数公里长的山脊如一尊巨佛仰卧苍穹。', tag: '十里天然卧佛' },
    culturalLandmark: { name: '洮州卫古城明代城垣遗址', description: '明代西陲最大屯兵古城池。', tag: '明代洮州古城' },
    ethnicFeatures: { costumes: '江淮遗风与藏式结合长衫', crafts: '拔河绳手工古法绞制（世界第一巨绳）', traditions: '万人拔河洮州古节（国家级非遗）', specialty: '临潭羊肚菌、当归猪肉' },
  }),
  createGansuCounty({
    id: 'zhuoni', name: '卓尼县', prefecture: '甘南藏族自治州', altitude: 2750,
    ethnicGroup: '藏族',
    mapCoord: { x: 0.36, y: -0.22, elevation: 0.57 }, terrainArchetype: 'forest',
    terrainType: '洮河九曲峡谷大林海与禅定古刹',
    terrainDescription: '滔滔洮河穿林过峡，觉乃藏族服饰华丽如孔雀开屏。',
    naturalLandmark: { name: '大峪沟九甸峡原始森林峡谷', description: '青山滴翠，流水击石，奇峰耸立。', tag: '大峪秀色' },
    culturalLandmark: { name: '禅定寺古刹与洮砚制作基地', description: '中国四大名砚之一【洮砚】之乡。', tag: '洮砚祖源禅定寺' },
    ethnicFeatures: { costumes: '觉乃藏族三格毛发饰与华丽鱼尾锦缎长袍', crafts: '国家级非遗【洮砚雕刻技艺】（老坑水归石鸭头绿）', traditions: '插箭节、洮砚祭坛礼', specialty: '卓尼黑木耳、洮砚老坑石' },
  }),
  createGansuCounty({
    id: 'zhouqu', name: '舟曲县', prefecture: '甘南藏族自治州', altitude: 1300,
    ethnicGroup: '藏族',
    mapCoord: { x: 0.44, y: -0.32, elevation: 0.38 }, terrainArchetype: 'canyon',
    terrainType: '白龙江高山深谷与藏乡江南花海',
    terrainDescription: '山水险峻，江峡清流，冬无严寒夏无酷暑。',
    naturalLandmark: { name: '翠峰山凌霄古刹与拉尕山高山草场', description: '奇峰如利剑插云，寺观隐于白云端。', tag: '翠峰凌霄' },
    culturalLandmark: { name: '舟曲东山转灯节古坛', description: '国家级非遗，数百盏灯阵如繁星游龙。', tag: '东山转灯古祭' },
    ethnicFeatures: { costumes: '舟曲藏族绣花百褶彩裙', crafts: '手工黑油柿饼风干压制', traditions: '正月十九迎婆婆、东山转灯', specialty: '舟曲从岭藏鸡、黑水橄榄' },
  }),
  createGansuCounty({
    id: 'diebu', name: '迭部县', prefecture: '甘南藏族自治州', altitude: 2400,
    ethnicGroup: '藏族',
    mapCoord: { x: 0.35, y: -0.30, elevation: 0.55 }, terrainArchetype: 'canyon',
    terrainType: '扎尕那天然石城巨石天险仙境',
    terrainDescription: '约瑟夫·洛克笔下的人间伊甸园，巨石如同天然城墙环抱藏寨。',
    naturalLandmark: { name: '扎尕那地质公园（天然石匣石城）', description: '巍峨灰白巨石山体如神造城阙，云遮雾障。', tag: '石匣仙境扎尕那' },
    culturalLandmark: { name: '腊子口天险战役旧址与纪念碑', description: '红军长征突破天险腊子口关键战役发生地。', tag: '天险腊子口' },
    ethnicFeatures: { costumes: '扎尕那传统鹿皮藏装、束彩色条纹腰带', crafts: '藏家纯木踏板房搭建技艺', traditions: '扎尕那插箭法会、神山祭祀', specialty: '迭部蕨麻猪（高原人参猪）、高山羊肚菌' },
  }),
  createGansuCounty({
    id: 'maqu', name: '玛曲县', prefecture: '甘南藏族自治州', altitude: 3450,
    ethnicGroup: '藏族',
    mapCoord: { x: 0.22, y: -0.32, elevation: 0.72 }, terrainArchetype: 'meadow',
    terrainType: '黄河九曲第一大回弯湿地草原',
    terrainDescription: '黄河在此回折大拐弯，百万亩水草湿地是河曲马的故乡。',
    naturalLandmark: { name: '天下黄河第一弯湿地国家公园', description: '黄河绕过阿尼玛卿雪峰折向东北，波光映斜阳。', tag: '黄河九曲第一弯' },
    culturalLandmark: { name: '西梅朵合塘万亩花海与格萨尔赛马场', description: '传说中格萨尔王称帝赛马的圣洁花原。', tag: '格萨尔王赛马场' },
    ethnicFeatures: { costumes: '河曲牧人厚皮藏袍、佩藏银錾花火镰', crafts: '牛毛粗帐篷手工织造', traditions: '格萨尔赛马大会、敬献哈达祭黄河', specialty: '河曲名马、阿万仓牦牛肉干' },
  }),
  createGansuCounty({
    id: 'luqu', name: '碌曲县', prefecture: '甘南藏族自治州', altitude: 3200,
    ethnicGroup: '藏族',
    mapCoord: { x: 0.26, y: -0.24, elevation: 0.67 }, terrainArchetype: 'meadow',
    terrainType: '尕海高原候鸟圣湖与则岔石林大峡谷',
    terrainDescription: '青藏高原东缘明镜，天鹅黑颈鹤栖息，石林刀削斧劈。',
    naturalLandmark: { name: '尕海湿地自然保护区与则岔石林天险', description: '神湖澄澈如碧玉，石峰拔地数百仞。', tag: '尕海神湖碧波' },
    culturalLandmark: { name: '郎木寺（甘肃侧达仓郎木寺与听风峡）', description: '白龙江发源地，横跨甘青两省的东方小瑞士。', tag: '郎木寺仙境' },
    ethnicFeatures: { costumes: '水獭皮领藏袍配天珠珊瑚串', crafts: '泥塑擦擦佛像翻模与藏香手工拉丝', traditions: '毛兰姆法会亮佛大典、瞻佛跳欠', specialty: '碌曲藏羊、高原酥油' },
  }),
  createGansuCounty({
    id: 'xiahe', name: '夏河县', prefecture: '甘南藏族自治州', altitude: 2900,
    ethnicGroup: '藏族',
    mapCoord: { x: 0.24, y: -0.16, elevation: 0.61 }, terrainArchetype: 'meadow',
    terrainType: '大夏河源桑科大草原与东方梵蒂冈',
    terrainDescription: '桑科草原无垠如海，拉卜楞寺金色琉璃顶在阳光下璀璨万道。',
    naturalLandmark: { name: '桑科草原与白石崖溶洞天险', description: '碧草连天，喀斯特白石溶洞出土古人类丹尼索瓦人骨。', tag: '桑科万顷碧原' },
    culturalLandmark: { name: '拉卜楞寺（世界藏学府）与超长转经长廊', description: '藏传佛教格鲁派六大宗主寺之一，世界最长转经筒长廊。', tag: '世界第一藏学府' },
    ethnicFeatures: { costumes: '华丽绛红紫缎藏袍、银质嘎乌盒佩胸', crafts: '酥油花纯手工微雕技艺、唐卡矿物彩绘', traditions: '正月十三晒佛节、辩经大法会', specialty: '夏河蹄筋、拉卜楞酥油点心' },
  }),
];
