import { CountyData, EthnicGroup, TerrainArchetype, WeatherType } from '../types';

interface RawCountyInput {
  id: string;
  name: string;
  prefecture: string;
  isAutonomous?: boolean;
  ethnicGroup?: EthnicGroup;
  altitude: number;
  mapCoord: { x: number; y: number; elevation: number };
  terrainArchetype: TerrainArchetype;
  terrainType: string;
  terrainDescription: string;
  naturalLandmark: { name: string; description: string; tag: string };
  culturalLandmark: { name: string; description: string; tag: string };
  ethnicFeatures: { costumes: string; crafts: string; traditions: string; specialty: string };
  weather?: WeatherType;
}

const archetypePalettes: Record<TerrainArchetype, { skyTop: string; skyBottom: string; mountainFar: string; mountainMid: string; ground: string; accent: string }> = {
  meadow: { skyTop: '#1e3a8a', skyBottom: '#93c5fd', mountainFar: '#cbd5e1', mountainMid: '#64748b', ground: '#365314', accent: '#eab308' },
  danxia: { skyTop: '#7c2d12', skyBottom: '#fdba74', mountainFar: '#9a3412', mountainMid: '#c2410c', ground: '#78350f', accent: '#fb923c' },
  forest: { skyTop: '#1e293b', skyBottom: '#64748b', mountainFar: '#94a3b8', mountainMid: '#334155', ground: '#14532d', accent: '#22c55e' },
  glacier: { skyTop: '#0f172a', skyBottom: '#38bdf8', mountainFar: '#f8fafc', mountainMid: '#7dd3fc', ground: '#bae6fd', accent: '#38bdf8' },
  gobi: { skyTop: '#451a03', skyBottom: '#fde047', mountainFar: '#78350f', mountainMid: '#a16207', ground: '#713f12', accent: '#f59e0b' },
  loess: { skyTop: '#78350f', skyBottom: '#fed7aa', mountainFar: '#a16207', mountainMid: '#b45309', ground: '#854d0e', accent: '#ea580c' },
  saltlake: { skyTop: '#0c4a6e', skyBottom: '#a5f3fc', mountainFar: '#e0f2fe', mountainMid: '#38bdf8', ground: '#f0fdfa', accent: '#06b6d4' },
  canyon: { skyTop: '#312e81', skyBottom: '#c7d2fe', mountainFar: '#4338ca', mountainMid: '#6366f1', ground: '#1e1b4b', accent: '#818cf8' },
};

function createQinghaiCounty(raw: RawCountyInput): CountyData {
  return {
    ...raw,
    province: '青海',
    isAutonomous: raw.isAutonomous ?? false,
    ethnicGroup: raw.ethnicGroup ?? '汉族/多元',
    weather: raw.weather ?? (raw.altitude > 3800 ? 'blizzard' : raw.altitude > 3200 ? 'light_snow' : 'clear'),
    bgPalette: archetypePalettes[raw.terrainArchetype],
  };
}

export const QINGHAI_COUNTIES: CountyData[] = [
  // 1. 西宁市 (7)
  createQinghaiCounty({
    id: 'chengdong_xn', name: '城东区', prefecture: '西宁市', altitude: 2260,
    mapCoord: { x: 0.16, y: 0.05, elevation: 0.48 }, terrainArchetype: 'canyon',
    terrainType: '湟水河谷东大门与古老回汉商贸集市',
    terrainDescription: '西宁开埠最早城区，依山傍水，湟水中流，回汉文化交融。',
    naturalLandmark: { name: '南山公园与凤凰台山峦', description: '青海高原首府制高点，俯瞰全城万家灯火。', tag: '凤台留云' },
    culturalLandmark: { name: '东关清真大寺', description: '西北四大清真大寺之一，古典宫殿与伊斯兰穹顶合璧。', tag: '东关大寺' },
    ethnicFeatures: { costumes: '纯白圆顶帽、彩绣绣花盖头', crafts: '金银细丝掐丝手工盘', traditions: '开斋盛宴、花儿清唱会', specialty: '西宁手抓羊肉、下窖干拌面' },
  }),
  createQinghaiCounty({
    id: 'chengzhong_xn', name: '城中区', prefecture: '西宁市', altitude: 2270,
    mapCoord: { x: 0.15, y: 0.04, elevation: 0.48 }, terrainArchetype: 'canyon',
    terrainType: '西宁古城隍庙心与南川河交汇处',
    terrainDescription: '明清西宁卫古城核心，南川河自拉脊山奔流而来。',
    naturalLandmark: { name: '南川河高柳夹岸水景', description: '高山雪水汇成绿带，依山傍郭。', tag: '南川碧浪' },
    culturalLandmark: { name: '西宁古城隍庙与总督行辕旧址', description: '明代西陲军政要枢遗存。', tag: '西宁古城隍' },
    ethnicFeatures: { costumes: '河湟农家青布坎肩', crafts: '西宁绒毛地毯编织', traditions: '城隍出巡大典', specialty: '青海老酸奶、尕面片' },
  }),
  createQinghaiCounty({
    id: 'chengxi_xn', name: '城西区', prefecture: '西宁市', altitude: 2280,
    mapCoord: { x: 0.14, y: 0.05, elevation: 0.49 }, terrainArchetype: 'canyon',
    terrainType: '高原现代文脉之芯与湟水清溪漫滩',
    terrainDescription: '高校院所聚集，河湟绿树成荫，气候宜人夏都名城。',
    naturalLandmark: { name: '西宁高原植物园高山杜鹃林', description: '收集青藏高原数千种耐寒珍稀花木。', tag: '高原奇葩' },
    culturalLandmark: { name: '青海省博物馆（三江源珍宝馆）', description: '珍藏青海舞蹈纹彩陶盆与宗喀巴金铜佛像。', tag: '青海历史之眼' },
    ethnicFeatures: { costumes: '现代时尚改良藏风锦缎坎肩', crafts: '堆绣唐卡工艺微缩画', traditions: '夏都清凉避暑节', specialty: '青稞奶茶、酿皮' },
  }),
  createQinghaiCounty({
    id: 'chengbei_xn', name: '城北区', prefecture: '西宁市', altitude: 2290,
    mapCoord: { x: 0.15, y: 0.07, elevation: 0.49 }, terrainArchetype: 'loess',
    terrainType: '北山九窟悬崖与烟雨红砂岩壁',
    terrainDescription: '北山危岩兀立，洞窟嵌于半空，中国第二大悬空寺。',
    naturalLandmark: { name: '北山烟雨红砂绝壁', description: '西宁古八景之一，云雾笼罩朱红石崖。', tag: '北山烟雨' },
    culturalLandmark: { name: '土楼观（北禅寺九窟十八洞）', description: '北魏始建的道释合一悬空石窟群。', tag: '中国第二悬空寺' },
    ethnicFeatures: { costumes: '道释居士棉袍布靴', crafts: '北山石雕与砂器烧制', traditions: '朝北山三月三庙会', specialty: '青海焜锅馍馍、狗浇尿饼' },
  }),
  createQinghaiCounty({
    id: 'huangzhong', name: '湟中区', prefecture: '西宁市', altitude: 2680,
    mapCoord: { x: 0.13, y: 0.02, elevation: 0.58 }, terrainArchetype: 'meadow',
    terrainType: '莲花山环抱藏传佛教圣地圣谷',
    terrainDescription: '八瓣莲花宝山环绕，金瓦殿在晨曦中金光万道。',
    naturalLandmark: { name: '群加国家级原始森林公园', description: '峰险林深，松柏参天，清泉长流。', tag: '群加秘境' },
    culturalLandmark: { name: '塔尔寺（宗喀巴大师诞生地）', description: '格鲁派六大宗主寺之一，“塔尔寺艺术三绝”（酥油花/壁画/堆绣）。', tag: '金瓦塔尔寺' },
    ethnicFeatures: { costumes: '绛红厚羊毛藏袍、金丝氆氇靴', crafts: '国家级非遗【酥油花雕刻】、【堆绣】、【加牙藏毯】', traditions: '正月十五酥油花灯会、转山大典', specialty: '湟中暖锅、蚕豆粉肉' },
  }),
  createQinghaiCounty({
    id: 'datong', name: '大通回族土族自治县', prefecture: '西宁市', altitude: 2460,
    isAutonomous: true, ethnicGroup: '土族',
    mapCoord: { x: 0.14, y: 0.10, elevation: 0.55 }, terrainArchetype: 'forest',
    terrainType: '娘娘山奇峰杜鹃与老爷山松涛峡谷',
    terrainDescription: '两山耸峙，大通河滔滔奔流，回族土族欢歌满川。',
    naturalLandmark: { name: '娘娘山高山草甸杜鹃天池', description: '夏日杜鹃花海漫向雪峰，金顶石崖耸天。', tag: '金顶娘娘山' },
    culturalLandmark: { name: '老爷山古建筑群与西北花儿会台', description: '六月六大通花儿歌会，西北最震撼民歌海洋。', tag: '西北花儿盛会' },
    ethnicFeatures: { costumes: '土族七彩花袖坎肩配绣花腰带', crafts: '土族盘绣花卉荷包、古法皮影', traditions: '六月六朝山花儿会、跳安代', specialty: '大通牦牛肉干、青稞油煎饼' },
  }),
  createQinghaiCounty({
    id: 'huangyuan', name: '湟源县', prefecture: '西宁市', altitude: 2630,
    mapCoord: { x: 0.08, y: 0.03, elevation: 0.60 }, terrainArchetype: 'canyon',
    terrainType: '日月山峡口茶马互市丹噶尔古城',
    terrainDescription: '农耕与游牧天然分界线，“海藏咽喉”，茶马互市盛极一时。',
    naturalLandmark: { name: '日月山分水岭天池', description: '文成公主入藏回望中原之地，日山月山两两相望。', tag: '日月神山' },
    culturalLandmark: { name: '丹噶尔古城（环海商都）与城隍庙', description: '保存极为完好的明清茶马商贸重镇。', tag: '茶马商都丹噶尔' },
    ethnicFeatures: { costumes: '皮商长袍佩羊皮披风', crafts: '国家级非遗【湟源排灯】（木雕彩绘走马玻璃宫灯）', traditions: '排灯民俗游会、茶马古道开市', specialty: '湟源陈醋（高原老陈醋）、酸辣里脊' },
  }),

  // 2. 海东市 (6)
  createQinghaiCounty({
    id: 'ledu', name: '乐都区', prefecture: '海东市', altitude: 2000,
    mapCoord: { x: 0.22, y: 0.04, elevation: 0.44 }, terrainArchetype: 'loess',
    terrainType: '湟水北岸古柳千顷与瞿昙神谷',
    terrainDescription: '乐都古称湟中重镇，湟水冲积平原肥美，古寺如金。',
    naturalLandmark: { name: '乐都南山天池与岗沟丹霞峡', description: '红岩峭拔，池水倒映远方雪山。', tag: '岗沟赤壁' },
    culturalLandmark: { name: '瞿昙寺（高原小故宫）', description: '明代皇家敕建古刹，御赐巨钟与巨幅永乐壁画。', tag: '高原小故宫' },
    ethnicFeatures: { costumes: '汉式宽袖盘扣棉衣配蓝花围裙', crafts: '乐都古法黑陶烧制与麦草画', traditions: '瞿昙寺六月法会、社火高抬', specialty: '乐都大樱桃、乐都沙果' },
  }),
  createQinghaiCounty({
    id: 'pingan', name: '平安区', prefecture: '海东市', altitude: 2150,
    mapCoord: { x: 0.19, y: 0.03, elevation: 0.46 }, terrainArchetype: 'loess',
    terrainType: '古驿站平原与白沈沟果园峡谷',
    terrainDescription: '古丝绸之路南道名驿，湟水支流滋养沃野瓜果。',
    naturalLandmark: { name: '古城峡黄河水峡与石峡飞瀑', description: '石壁高耸，江流如雷鸣。', tag: '古城险峡' },
    culturalLandmark: { name: '海东平安驿·河湟民俗文化小镇', description: '全方位再现河湟古道驿站与农耕民俗。', tag: '河湟第一驿' },
    ethnicFeatures: { costumes: '河湟农家羊皮袄坎肩', crafts: '手工泥塑彩绘兔儿爷', traditions: '平安驿春社社火', specialty: '平安牛头肉、柴火大月饼' },
  }),
  createQinghaiCounty({
    id: 'minhe', name: '民和回族土族自治县', prefecture: '海东市', altitude: 1750,
    isAutonomous: true, ethnicGroup: '土族',
    mapCoord: { x: 0.26, y: -0.01, elevation: 0.40 }, terrainArchetype: 'canyon',
    terrainType: '三江之源东部门户喇家史前遗址',
    terrainDescription: '青海东大门，黄河自南切开积石峡，气候温和。',
    naturalLandmark: { name: '黄河积石峡口与七彩峰峦', description: '黄河水在此如玉带绕绿洲。', tag: '积石大门' },
    culturalLandmark: { name: '喇家国家考古遗址（东方庞贝）', description: '距今4000年史前地震遗址，出土世界第一碗面条。', tag: '东方庞贝喇家' },
    ethnicFeatures: { costumes: '土族五彩花袖袍配白底绣花帽', crafts: '史前骨针刺绣复原技法', traditions: '土族纳顿节（世界上最长的狂欢节）', specialty: '民和肉桃、民和旱砂西瓜' },
  }),
  createQinghaiCounty({
    id: 'huzhu', name: '互助土族自治县', prefecture: '海东市', altitude: 2500,
    isAutonomous: true, ethnicGroup: '土族',
    mapCoord: { x: 0.18, y: 0.08, elevation: 0.54 }, terrainArchetype: 'forest',
    terrainType: '北山林海高山杜鹃与彩虹之乡',
    terrainDescription: '全国唯一的土族自治县，七彩花袖与轮子秋如彩虹降落人间。',
    naturalLandmark: { name: '互助北山国家森林地质公园', description: '原始针叶林覆盖率极高，浪士当神瀑如练。', tag: '青海九寨北山' },
    culturalLandmark: { name: '彩虹部落土族园与佑宁寺古刹', description: '展示土族国家级非遗【盘绣】与惊险【轮子秋】。', tag: '彩虹故乡土族园' },
    ethnicFeatures: { costumes: '土族七彩花袖衣、绣花彩靴、扭达头饰', crafts: '国家级非遗【土族盘绣】（两针交织密如珠玑）', traditions: '国家级非遗【轮子秋】旋转竞技、丹麻花儿会', specialty: '互助青稞酩馏酒（国家名酒）、萱麻饼' },
  }),
  createQinghaiCounty({
    id: 'hualong', name: '化隆回族自治县', prefecture: '海东市', altitude: 2050,
    isAutonomous: true, ethnicGroup: '回族',
    mapCoord: { x: 0.22, y: -0.02, elevation: 0.45 }, terrainArchetype: 'canyon',
    terrainType: '黄河公伯峡大峡谷与中国拉面之乡',
    terrainDescription: '两山对峙如天门，黄河从峡谷穿流，数十万拉面匠走出深山。',
    naturalLandmark: { name: '公伯峡黄河红岩大峡谷', description: '悬崖峭壁如刀劈，碧水波澜万丈。', tag: '公伯神峡' },
    culturalLandmark: { name: '夏琼寺（宗喀巴大师剃度出家地）', description: '建于黄河峭壁之巅的金顶古刹，俯瞰大河奔流。', tag: '悬崖夏琼寺' },
    ethnicFeatures: { costumes: '回族平顶白帽配精干蓝棉袄', crafts: '化隆传统拉面古法和面溜条十八法', traditions: '黄河开河节、拉面匠技能大赛', specialty: '化隆牛肉拉面、黄河冷水红鳟' },
  }),
  createQinghaiCounty({
    id: 'xunhua', name: '循化撒拉族自治县', prefecture: '海东市', altitude: 1800,
    isAutonomous: true, ethnicGroup: '撒拉族',
    mapCoord: { x: 0.23, y: -0.05, elevation: 0.42 }, terrainArchetype: 'forest',
    terrainType: '积石山黄河谷地与孟达天池翡翠仙池',
    terrainDescription: '撒拉族白驼泉传说故乡，红线椒如火，天池碧波万顷。',
    naturalLandmark: { name: '孟达天池国家级自然保护区', description: '高原西双版纳，群山环抱一泓神湖碧玉。', tag: '青藏高原西双版纳' },
    culturalLandmark: { name: '街子清真大寺与骆驼泉遗址', description: '藏有珍贵手抄本《古兰经》，白驼化泉神迹地。', tag: '撒拉源头骆驼泉' },
    ethnicFeatures: { costumes: '撒拉族红绿坎肩、宽大绣花围裙、头戴素黑戴斯达尔', crafts: '撒拉族古法篱笆楼木石营建工法', traditions: '婚礼“骆驼戏”、撒拉艳姑民歌对唱', specialty: '循化红线椒（中华第一椒）、核桃' },
  }),

  // 3. 海北藏族自治州 (4)
  createQinghaiCounty({
    id: 'menyuan', name: '门源回族自治县', prefecture: '海北藏族自治州', altitude: 2850,
    isAutonomous: true, ethnicGroup: '回族',
    mapCoord: { x: 0.10, y: 0.18, elevation: 0.62 }, terrainArchetype: 'meadow',
    terrainType: '百里油菜花海金川与岗什卡雪峰冷杉',
    terrainDescription: '祁连山南麓浩门河谷，盛夏六十万亩油菜花如金色汪洋。',
    naturalLandmark: { name: '岗什卡雪峰（海拔5254米）与百里花海', description: '祁连冷龙岭第一峰，白雪映照黄金巨毯。', tag: '岗什卡雪峰' },
    culturalLandmark: { name: '浩门古城遗址与照壁山观花台', description: '古代丝路军马互市重关。', tag: '百里金花照壁' },
    ethnicFeatures: { costumes: '回汉游牧皮袄、白布顶帽', crafts: '高山优质百花蜜割取', traditions: '门源油菜花旅游节、华热藏族欢歌', specialty: '门源百里油菜花蜜、门源奶皮' },
  }),
  createQinghaiCounty({
    id: 'qilian_xian', name: '祁连县', prefecture: '海北藏族自治州', altitude: 2900,
    ethnicGroup: '藏族',
    mapCoord: { x: -0.05, y: 0.25, elevation: 0.65 }, terrainArchetype: 'glacier',
    terrainType: '东方小瑞士卓尔山赤壁与阿咪东索神山',
    terrainDescription: '天境祁连，阿咪东索终年积雪，卓尔山赤壁丹霞如赤锦铺地。',
    naturalLandmark: { name: '卓尔山丹霞红崖与阿咪东索雪峰', description: '雪山、森林、草原与赭红丹霞四美合一。', tag: '东方小瑞士' },
    culturalLandmark: { name: '阿咪东索经幡群与拉加寺分寺', description: '藏传佛教神山转山圣地。', tag: '阿咪东索神山' },
    ethnicFeatures: { costumes: '传统藏式华美水獭皮边氆氇长袍', crafts: '祁连黄玉天然石雕刻', traditions: '神山转山祭典、草原赛马会', specialty: '祁连藏羊肉、八宝黄菇' },
  }),
  createQinghaiCounty({
    id: 'haiyan', name: '海晏县', prefecture: '海北藏族自治州', altitude: 3050,
    ethnicGroup: '藏族',
    mapCoord: { x: 0.05, y: 0.12, elevation: 0.66 }, terrainArchetype: 'meadow',
    terrainType: '金银滩大草原与青海湖北岸金沙湾',
    terrainDescription: '王洛宾先生创作《在那遥远的地方》之地，中国两弹一星摇篮。',
    naturalLandmark: { name: '金银滩草原万亩白银金露梅花海', description: '白花似银，黄花似金，湖水微波拍岸。', tag: '金银滩花海' },
    culturalLandmark: { name: '原子城西海镇旧址（两弹一星基地）', description: '我国第一个核武器研制基地纪念馆。', tag: '两弹一星摇篮' },
    ethnicFeatures: { costumes: '藏式皮裘长袍束彩绸带', crafts: '金银滩牛羊毛手工毡画', traditions: '王洛宾情歌音乐节', specialty: '海晏青稞白酒、生烤羊排' },
  }),
  createQinghaiCounty({
    id: 'gangcha', name: '刚察县', prefecture: '海北藏族自治州', altitude: 3280,
    ethnicGroup: '藏族',
    mapCoord: { x: -0.08, y: 0.15, elevation: 0.69 }, terrainArchetype: 'meadow',
    terrainType: '青海湖湟鱼洄游第一江沙柳河湿地',
    terrainDescription: '青海湖北岸水草丰盛，数十万条高原裸鲤逆流跃龙门。',
    naturalLandmark: { name: '沙柳河半河清水半河鱼奇观', description: '青海湖湟鱼洄游排山倒海，黑颈鹤临水觅食。', tag: '湟鱼洄游圣境' },
    culturalLandmark: { name: '刚察湟鱼家园与仓央嘉措文化广场', description: '传唱仓央嘉措动人情诗的圣湖之滨。', tag: '仓央嘉措诗泉' },
    ethnicFeatures: { costumes: '藏北牧人宽皮领藏袍配青金石发辫', crafts: '湟鱼骨质环保艺术雕饰', traditions: '青海湖祭湖神典、观鱼节', specialty: '刚察牦牛黄油、手抓羊肉' },
  }),

  // 4. 黄南藏族自治州 (4)
  createQinghaiCounty({
    id: 'tongren_shi', name: '同仁市', prefecture: '黄南藏族自治州', altitude: 2480,
    ethnicGroup: '藏族',
    mapCoord: { x: 0.19, y: -0.12, elevation: 0.54 }, terrainArchetype: 'canyon',
    terrainType: '隆务河谷世界非遗热贡艺术摇篮',
    terrainDescription: '“家家画唐卡，户户飘墨香”，联合国人类非遗热贡艺术之都。',
    naturalLandmark: { name: '麦秀原始林海国家森林公园', description: '苍松翠柏，峰回路转，溪水潺潺。', tag: '麦秀林涛' },
    culturalLandmark: { name: '隆务寺大经堂与吾屯下寺画院', description: '藏传佛教名刹，热贡唐卡泥塑堆绣最高殿堂。', tag: '热贡艺术宗源' },
    ethnicFeatures: { costumes: '华丽彩绣藏袍配红珊瑚头饰', crafts: '人类非遗【热贡唐卡彩绘】（金汁研磨/矿物神笔）', traditions: '六月会“於菟”古巫舞、晒大佛', specialty: '同仁冬虫夏草、黄果梨' },
  }),
  createQinghaiCounty({
    id: 'jianzha', name: '尖扎县', prefecture: '黄南藏族自治州', altitude: 2020,
    ethnicGroup: '藏族',
    mapCoord: { x: 0.18, y: -0.07, elevation: 0.46 }, terrainArchetype: 'danxia',
    terrainType: '坎布拉国家地质公园奇峰丹霞与神木林',
    terrainDescription: '黄河李家峡水库碧蓝如琉璃，赤壁丹霞如千座城堡倒映水中。',
    naturalLandmark: { name: '坎布拉丹霞群峰与龟山奇绝', description: '丹霞峰丛耸立千仞，红崖碧水天地绝唱。', tag: '坎布拉神秀' },
    culturalLandmark: { name: '阿琼南宗尼姑寺与南宗扎寺', description: '藏传佛教“后弘期”发祥圣地。', tag: '南宗神崖古刹' },
    ethnicFeatures: { costumes: '藏式藏服佩古铜神弓护腕', crafts: '国家级非遗【尖扎达尔尕五彩神弓制作】', traditions: '五彩神弓射箭节（中国五彩神弓之乡）', specialty: '尖扎达吉香醋、李家峡红鳟' },
  }),
  createQinghaiCounty({
    id: 'zeku', name: '泽库县', prefecture: '黄南藏族自治州', altitude: 3660,
    ethnicGroup: '藏族',
    mapCoord: { x: 0.12, y: -0.18, elevation: 0.74 }, terrainArchetype: 'meadow',
    terrainType: '泽曲高寒纯净大草甸与和日石经圣墙',
    terrainDescription: '地处高寒纯净牧区，世界最长石刻大藏经墙横贯草原。',
    naturalLandmark: { name: '泽曲河湿地国家级自然保护区', description: '蜿蜒如带，黑颈鹤与雪豹共存的净土。', tag: '泽曲天境' },
    culturalLandmark: { name: '和日寺石经墙（世界石刻之最）', description: '僧俗两代历时数十年雕刻的数百米玛尼石大经墙。', tag: '天下第一石经墙' },
    ethnicFeatures: { costumes: '厚实原生态羊毛大藏皮袍', crafts: '国家级非遗【和日石雕技艺】', traditions: '和日神舞、草原放牧对歌', specialty: '泽库黑牦牛肉、雪白酥油' },
  }),
  createQinghaiCounty({
    id: 'henan_menggu', name: '河南蒙古族自治县', prefecture: '黄南藏族自治州', altitude: 3600,
    isAutonomous: true, ethnicGroup: '蒙古族',
    mapCoord: { x: 0.12, y: -0.25, elevation: 0.72 }, terrainArchetype: 'meadow',
    terrainType: '黄河大拐弯外围丰美水草甸草原',
    terrainDescription: '青海唯一的纯蒙古族自治县，黄河九曲外侧优质有机牧场。',
    naturalLandmark: { name: '洮河源国家湿地公园与吉岗草甸', description: '牛羊遍野、水草繁茂的纯净高山水甸。', tag: '天然水草胜境' },
    culturalLandmark: { name: '亲王府遗址与圣湖仙女洞', description: '河南蒙旗亲王统辖遗迹与藏蒙交融文化。', tag: '蒙旗王府古迹' },
    ethnicFeatures: { costumes: '德都蒙古袍配藏式金银嵌珊瑚马鞍饰', crafts: '蒙古马鞍手工包银与马鬃绳编织', traditions: '那达慕大会、敖包大祭、祝词赞诵', specialty: '河曲名马、雪多牦牛肉、欧拉大羊肉' },
  }),

  // 5. 海南藏族自治州 (5)
  createQinghaiCounty({
    id: 'gonghe', name: '共和县', prefecture: '海南藏族自治州', altitude: 2880,
    ethnicGroup: '藏族',
    mapCoord: { x: 0.02, y: 0.02, elevation: 0.62 }, terrainArchetype: 'meadow',
    terrainType: '青海湖南岸万顷碧波与龙羊峡水电明珠',
    terrainDescription: '高原湖滨重镇，北濒青海湖，南扼龙羊峡黄河险滩。',
    naturalLandmark: { name: '青海湖二郎剑半岛与黑马河日出', description: '浩瀚碧蓝湖水如同高原蓝宝石。', tag: '青海湖皇冠' },
    culturalLandmark: { name: '龙羊峡黄河大峡谷与天下第一坝', description: '黄河第一大水电枢纽与深不可测的赤壁石峡。', tag: '龙羊天险' },
    ethnicFeatures: { costumes: '藏式皮面大袍配绿松石发链', crafts: '黄河石微雕与羊毛藏毯', traditions: '青海湖祭湖节、赛马会', specialty: '龙羊峡三文鱼、青海湖裸鲤泉茶' },
  }),
  createQinghaiCounty({
    id: 'tongde', name: '同德县', prefecture: '海南藏族自治州', altitude: 3100,
    ethnicGroup: '藏族',
    mapCoord: { x: 0.08, y: -0.15, elevation: 0.65 }, terrainArchetype: 'canyon',
    terrainType: '黄河深切峡谷宗日石器文化胜地',
    terrainDescription: '黄河绕同德奔流，史前宗日文化出土双人抬物彩陶盆。',
    naturalLandmark: { name: '河北林场高山原始云杉峡谷', description: '密林遮天，溪流在峭壁石间回旋。', tag: '河北清凉林海' },
    culturalLandmark: { name: '宗日遗址与石藏寺古刹', description: '五千年史前青海本土彩陶文化发祥地。', tag: '宗日彩陶源' },
    ethnicFeatures: { costumes: '原始质朴大羊毛坎肩藏服', crafts: '古陶复模与石器打制', traditions: '宗日丰收节、嘛呢法会', specialty: '同德巴什羊、高山蕨麻' },
  }),
  createQinghaiCounty({
    id: 'guide', name: '贵德县', prefecture: '海南藏族自治州', altitude: 2200,
    mapCoord: { x: 0.12, y: -0.04, elevation: 0.47 }, terrainArchetype: 'danxia',
    terrainType: '天下黄河贵德清七彩峰林绿洲',
    terrainDescription: '“天下黄河贵德清”，江水碧绿如翡翠，两岸丹霞似火。',
    naturalLandmark: { name: '贵德国家地质公园七彩阿什贡丹霞', description: '大地血脉纵横，奇峰怪石倒映碧清黄河。', tag: '天下黄河贵德清' },
    culturalLandmark: { name: '贵德明清古城与玉皇阁古建筑群', description: '历经数百年兵燹依然完好无损的三层木构重檐殿阁。', tag: '古阁凌空' },
    ethnicFeatures: { costumes: '汉藏结合青缎长衫', crafts: '黄河奇石底座雕刻', traditions: '贵德梨花节、黄河放灯', specialty: '贵德长把梨、贵德软儿梨' },
  }),
  createQinghaiCounty({
    id: 'xinghai', name: '兴海县', prefecture: '海南藏族自治州', altitude: 3300,
    ethnicGroup: '藏族',
    mapCoord: { x: -0.05, y: -0.08, elevation: 0.70 }, terrainArchetype: 'meadow',
    terrainType: '赛宗神山险峰与子科滩高原大牧场',
    terrainDescription: '安多藏区名刹赛宗寺立于绝壁，神山雪线环绕草原。',
    naturalLandmark: { name: '赛宗神山猴石峰奇绝', description: '奇石千姿百态，藏羚羊雪豹出没林岩。', tag: '赛宗神石' },
    culturalLandmark: { name: '赛宗寺与大河坝古烽火台', description: '藏传佛教安多三大神山之一圣寺。', tag: '赛宗圣地' },
    ethnicFeatures: { costumes: '厚羊毛白皮藏袍', crafts: '牦牛绒手工纯毛编织绳', traditions: '赛宗转山节、祭山神大典', specialty: '兴海牦牛肉干、高原黑青稞' },
  }),
  createQinghaiCounty({
    id: 'guinan', name: '贵南县', prefecture: '海南藏族自治州', altitude: 3100,
    ethnicGroup: '藏族',
    mapCoord: { x: 0.06, y: -0.08, elevation: 0.65 }, terrainArchetype: 'gobi',
    terrainType: '穆格滩浩瀚黄沙与黄沙锁龙治沙绿洲',
    terrainDescription: '茫茫沙丘如金色瀚海，数十载治沙筑起绿色长城。',
    naturalLandmark: { name: '茫拉河大峡谷与穆格滩沙丘林', description: '深峡幽暗壁立，黄沙绿树相映生辉。', tag: '茫拉绝壁' },
    culturalLandmark: { name: '托勒寺金瓦殿与治沙丰碑', description: '草原深处清幽庄严的藏传古寺。', tag: '治沙奇迹' },
    ethnicFeatures: { costumes: '防沙羊皮风帽配藏袍', crafts: '防风柳条固沙方格编织', traditions: '草原黑藏羊开牧节', specialty: '贵南黑藏羊肉（地理标志极品）、芫荽' },
  }),

  // 6. 果洛藏族自治州 (6)
  createQinghaiCounty({
    id: 'maqin', name: '玛沁县', prefecture: '果洛藏族自治州', altitude: 3750,
    ethnicGroup: '藏族',
    mapCoord: { x: 0.05, y: -0.32, elevation: 0.78 }, terrainArchetype: 'glacier',
    terrainType: '阿尼玛卿雪山主峰终年极地冰川',
    terrainDescription: '藏区四大神山之一，海拔6282米，冰峰林立直插苍穹。',
    naturalLandmark: { name: '阿尼玛卿主峰与哈龙冰川瀑布', description: '万古雪山晶莹夺目，极高山冰川裂缝泛着幽蓝圣光。', tag: '阿尼玛卿雪山' },
    culturalLandmark: { name: '拉加寺（黄河第一古刹）', description: '黄河上游北岸格鲁派著名大寺。', tag: '黄河大寺拉加' },
    ethnicFeatures: { costumes: '果洛特色高领宽袖虎皮包边藏皮袍', crafts: '藏族牛角角雕与纯铜酥油灯铸造', traditions: '阿尼玛卿转山大典、格萨尔说唱', specialty: '果洛大黄、阿尼玛卿雪菊' },
  }),
  createQinghaiCounty({
    id: 'banma', name: '班玛县', prefecture: '果洛藏族自治州', altitude: 3500,
    ethnicGroup: '藏族',
    mapCoord: { x: 0.16, y: -0.42, elevation: 0.73 }, terrainArchetype: 'forest',
    terrainType: '玛可河原始森林林海与藏式碉楼古寨',
    terrainDescription: '三江源唯一的原始落叶阔叶与针叶密林，天然红军石刻路。',
    naturalLandmark: { name: '玛可河国家级自然保护区', description: '重峦叠嶂，古木参天，溪流湍急。', tag: '三江源绿肺' },
    culturalLandmark: { name: '班玛藏家碉楼古村落群与红军沟', description: '石木结构的千年高耸藏碉，红军石刻标语犹存。', tag: '班玛百年藏碉' },
    ethnicFeatures: { costumes: '藏式彩绣花领宽袍配鹿皮短腰带', crafts: '国家级非遗【班玛藏族传统黑陶制作】', traditions: '藏历新年煨桑祈福、射响箭', specialty: '班玛藏雪茶（高原古茶）、羊肚菌' },
  }),
  createQinghaiCounty({
    id: 'gande', name: '甘德县', prefecture: '果洛藏族自治州', altitude: 4050,
    ethnicGroup: '藏族',
    mapCoord: { x: 0.08, y: -0.38, elevation: 0.83 }, terrainArchetype: 'meadow',
    terrainType: '格萨尔文化之乡高原大湿地草甸',
    terrainDescription: '海拔超过四千米，格萨尔史诗活态流传的雪域高原。',
    naturalLandmark: { name: '班玛仁脱神山与班玛仁脱湖', description: '神山倒映圣湖，雪水如乳，万千候鸟驻留。', tag: '神山圣湖' },
    culturalLandmark: { name: '格萨尔狮龙宫殿与东吉多卡寺', description: '传说中格萨尔王的大殿旧址复建地。', tag: '格萨尔王宫殿' },
    ethnicFeatures: { costumes: '佩带金银刀鞘与格萨尔战袍风范长衫', crafts: '格萨尔说唱木雕版刻印', traditions: '格萨尔史诗连唱三天大典', specialty: '甘德牦牛肉干、雪山冬虫夏草' },
  }),
  createQinghaiCounty({
    id: 'dari', name: '达日县', prefecture: '果洛藏族自治州', altitude: 3960,
    ethnicGroup: '藏族',
    mapCoord: { x: 0.02, y: -0.42, elevation: 0.81 }, terrainArchetype: 'meadow',
    terrainType: '黄河上游宽谷大草原与查朗古刹',
    terrainDescription: '大河源头水流平缓，万顷水草连天，黑帐篷炊烟袅袅。',
    naturalLandmark: { name: '达日黄河第一大桥古滩', description: '奔腾黄河在此汇聚，两岸牛羊成群。', tag: '大河源头宽川' },
    culturalLandmark: { name: '查朗寺大殿与格萨尔林卡', description: '藏传佛教古刹，藏有大量古代手抄经卷。', tag: '查朗佛国' },
    ethnicFeatures: { costumes: '宽厚黑羊皮藏袍、腰束藏银镶珊瑚皮带', crafts: '纯手工牦牛毛捻线编织黑帐篷', traditions: '迎神插箭节、草原锅庄舞', specialty: '达日高原羊肉、纯天然酥油' },
  }),
  createQinghaiCounty({
    id: 'jiuzhi', name: '久治县', prefecture: '果洛藏族自治州', altitude: 3600,
    ethnicGroup: '藏族',
    mapCoord: { x: 0.14, y: -0.36, elevation: 0.74 }, terrainArchetype: 'glacier',
    terrainType: '年保玉则天神后花园巨峰仙女湖',
    terrainDescription: '怪石嶙峋如刀削，冰川融水化为数百处高山晶莹海子。',
    naturalLandmark: { name: '年保玉则仙女湖与妖女湖神境', description: '黑色花岗岩尖峰刺破青天，湖畔繁花锦簇。', tag: '天神后花园' },
    culturalLandmark: { name: '白玉寺与年保玉则神山坛城', description: '藏传佛教宁玛派名寺，金碧辉煌。', tag: '白玉古寺' },
    ethnicFeatures: { costumes: '华丽水貂皮边藏服、配佩九眼天珠', crafts: '藏银雕刻花纹奶茶壶', traditions: '仙女湖祭神湖祈愿节', specialty: '久治牦牛肉、高山黄芪' },
  }),
  createQinghaiCounty({
    id: 'maduo', name: '玛多县', prefecture: '果洛藏族自治州', altitude: 4270,
    ethnicGroup: '藏族',
    mapCoord: { x: -0.12, y: -0.28, elevation: 0.86 }, terrainArchetype: 'glacier',
    terrainType: '黄河源头千湖之县扎陵湖鄂陵湖',
    terrainDescription: '海拔超过四千米，万里黄河正源发祥地，湖泊星罗棋布。',
    naturalLandmark: { name: '黄河源头姊妹湖（扎陵湖与鄂陵湖）', description: '纯净高原碧蓝如镜，牛头碑矗立于两湖之间措日尕则山巅。', tag: '天下黄河之源' },
    culturalLandmark: { name: '黄河源牛头铜碑与文成公主柏海迎亲古地', description: '唐蕃古道松赞干布亲自迎接文成公主入藏历史见证。', tag: '唐蕃古道柏海迎亲' },
    ethnicFeatures: { costumes: '厚重双层藏毛皮袍、防雪盲金丝皮帽', crafts: '玛尼石纯手工雕刻六字真言', traditions: '黄河源头祭水盛典、雪域祈安法会', specialty: '高寒藏羊肉、高原雪参' },
  }),

  // 7. 玉树藏族自治州 (6)
  createQinghaiCounty({
    id: 'yushu_shi', name: '玉树市', prefecture: '玉树藏族自治州', altitude: 3700,
    ethnicGroup: '藏族',
    mapCoord: { x: -0.25, y: -0.45, elevation: 0.76 }, terrainArchetype: 'canyon',
    terrainType: '巴塘河与通天河交汇玉树结古古镇',
    terrainDescription: '唐蕃古道重镇结古，嘉那玛尼石堆如城墙耸立。',
    naturalLandmark: { name: '巴塘草原百花滩与通天河大拐弯', description: '西游记渡通天河处，水声隆隆气势非凡。', tag: '通天大河' },
    culturalLandmark: { name: '新寨嘉那玛尼石堆（吉尼斯世界纪录）', description: '拥有逾25亿块六字真言玛尼石构成的宏伟石城。', tag: '天下第一玛尼堆' },
    ethnicFeatures: { costumes: '玉树康巴藏袍（男佩金银九环刀，女饰华美珊瑚顶头饰）', crafts: '国家级非遗【玉树藏族服饰制作】、【铜器錾刻】', traditions: '玉树康巴赛马节、锅庄歌舞之乡', specialty: '玉树冬虫夏草（全国顶级品质）、藏羊皮袄' },
  }),
  createQinghaiCounty({
    id: 'zaduo', name: '杂多县', prefecture: '玉树藏族自治州', altitude: 4060,
    ethnicGroup: '藏族',
    mapCoord: { x: -0.38, y: -0.52, elevation: 0.82 }, terrainArchetype: 'glacier',
    terrainType: '澜沧江发源地中国雪豹之乡吉富峡谷',
    terrainDescription: '一江清水向南奔流入东南亚湄公河，野生雪豹密集栖息地。',
    naturalLandmark: { name: '澜沧江源头扎阿曲与昂赛丹霞大峡谷', description: '高原红色丹霞地貌，雪豹在悬崖岩缝出没。', tag: '澜沧江源大峡谷' },
    culturalLandmark: { name: '昂赛古石刻岩画与查旦湿地祈愿坛', description: '古代游牧民族在崖壁留下的凿刻狩猎岩画。', tag: '昂赛岩画' },
    ethnicFeatures: { costumes: '康巴皮袍短衫，腰间别牛角火药筒', crafts: '纯银饰品精细打磨', traditions: '杂多雪豹文化节、虫草开山节', specialty: '杂多特级冬虫夏草、牦牛干巴' },
  }),
  createQinghaiCounty({
    id: 'chengduo', name: '称多县', prefecture: '玉树藏族自治州', altitude: 3850,
    ethnicGroup: '藏族',
    mapCoord: { x: -0.18, y: -0.40, elevation: 0.78 }, terrainArchetype: 'meadow',
    terrainType: '通天河古渡口与拉布古藏村寨',
    terrainDescription: '通天河两岸石壁如削，古老藏式石砌碉楼错落梯田间。',
    naturalLandmark: { name: '通天河晒经石与古樟大石峡', description: '相传唐僧取经渡河被老鼋所翻，晒经石印痕犹存。', tag: '晒经石天工' },
    culturalLandmark: { name: '赛康寺与嘎朵觉悟神山圣迹', description: '藏区四大神山之一嘎朵觉悟守护之城。', tag: '嘎朵觉悟神山' },
    ethnicFeatures: { costumes: '康巴宽袖藏红袍、银包珊瑚腰带', crafts: '称多手工石雕与手工打酥油桶', traditions: '嘎朵觉悟转山大典', specialty: '通天河红盐、生牦牛肉干' },
  }),
  createQinghaiCounty({
    id: 'zhiduo', name: '治多县', prefecture: '玉树藏族自治州', altitude: 4200,
    ethnicGroup: '藏族',
    mapCoord: { x: -0.42, y: -0.38, elevation: 0.85 }, terrainArchetype: 'glacier',
    terrainType: '万里长江正源可可西里无人区大门',
    terrainDescription: '“万里长江第一县”，沱沱河涓涓细流自格拉丹东冰峰流出。',
    naturalLandmark: { name: '长江正源沱沱河与各拉丹冬雪峰冰川', description: '万刃玄冰在阳光下泛着七彩宝光，中华母亲河正源。', tag: '万里长江之源' },
    culturalLandmark: { name: '索南达杰自然保护站与环保烈士丰碑', description: '为守护可可西里藏羚羊献出生命的环保英雄纪念地。', tag: '可可西里卫士' },
    ethnicFeatures: { costumes: '极地抗极寒加厚长毛皮袍、狐皮围耳帽', crafts: '牦牛毛手工纺线制绳技艺', traditions: '藏羚羊迁徙护送祭礼', specialty: '高原风干手抓肉、治多雪茶' },
  }),
  createQinghaiCounty({
    id: 'nangqian', name: '囊谦县', prefecture: '玉树藏族自治州', altitude: 3640,
    ethnicGroup: '藏族',
    mapCoord: { x: -0.28, y: -0.58, elevation: 0.75 }, terrainArchetype: 'forest',
    terrainType: '澜沧江水系扎曲河谷与千年古红盐田',
    terrainDescription: '玉树唯一气候温和森林覆盖之地，出产名贵天然红盐。',
    naturalLandmark: { name: '麦曲峡谷与乃加玛神山雪岩', description: '高山温泉喷涌，悬崖翠柏密布。', tag: '乃加玛秀峡' },
    culturalLandmark: { name: '达那寺（格萨尔王大将群墓地）与千年达那盐田', description: '建于悬崖峭壁的古老寺院，藏有格萨尔铠甲战盔。', tag: '格萨尔大将古墓' },
    ethnicFeatures: { costumes: '藏式锦缎修身袍配天然红盐晶手串', crafts: '千年古法高山天日晒盐技艺（国家级非遗）', traditions: '开盐池祭礼、达那法舞', specialty: '囊谦藏红盐（千年古盐）、藏蜜' },
  }),
  createQinghaiCounty({
    id: 'qumalai', name: '曲麻莱县', prefecture: '玉树藏族自治州', altitude: 4220,
    ethnicGroup: '藏族',
    mapCoord: { x: -0.32, y: -0.35, elevation: 0.85 }, terrainArchetype: 'glacier',
    terrainType: '黄河源正源卡日曲与可可西里野牦牛故里',
    terrainDescription: '黄河最长支流卡日曲源出此地，高天厚土，荒原辽阔。',
    naturalLandmark: { name: '卡日曲黄河正源第一甘泉与约古宗列盆地', description: '清泉从石砾中汩汩涌出，化为九曲黄河。', tag: '卡日曲水脉' },
    culturalLandmark: { name: '黄河正源石碑与宗开神山坛城', description: '地理学家与探险家立下的黄河正源国家地理标志。', tag: '黄河发源石碑' },
    ethnicFeatures: { costumes: '野牦牛皮毛混纺特制雪地防风大皮衣', crafts: '藏族马鞭编织与纯牛毛马甲', traditions: '祭祀卡日曲甘泉、野牦牛舞', specialty: '曲麻莱藏羊肉、野血牦牛肉' },
  }),

  // 8. 海西蒙古族藏族自治州 (7)
  createQinghaiCounty({
    id: 'geermu_shi', name: '格尔木市', prefecture: '海西蒙古族藏族自治州', altitude: 2800,
    mapCoord: { x: -0.45, y: 0.05, elevation: 0.56 }, terrainArchetype: 'saltlake',
    terrainType: '察尔汗万丈盐桥与昆仑山地质圣境',
    terrainDescription: '戈壁新城，柴达木盆地心脏，南控巍巍万山之祖昆仑山。',
    naturalLandmark: { name: '察尔汗天然盐湖与万丈盐桥奇观', description: '面积达数千平方公里的绿色卤水盐沼，盐路平坦如砥。', tag: '察尔汗盐海' },
    culturalLandmark: { name: '昆仑山口（索南达杰雕像）与无极龙凤宫', description: '道教万神祖庭与可可西里雪山大门。', tag: '万山之祖昆仑' },
    ethnicFeatures: { costumes: '工矿坚韧夹克配蒙古族驼绒坎肩', crafts: '天然结晶盐雕与昆仑玉手工雕刻', traditions: '昆仑文化寻根大典', specialty: '格尔木枸杞（红枸杞与黑枸杞王）、昆仑玉' },
  }),
  createQinghaiCounty({
    id: 'delingha_shi', name: '德令哈市', prefecture: '海西蒙古族藏族自治州', altitude: 2980,
    mapCoord: { x: -0.22, y: 0.18, elevation: 0.60 }, terrainArchetype: 'meadow',
    terrainType: '巴音河穿流戈壁明珠与可鲁克湖托素湖',
    terrainDescription: '海子诗歌“姐姐，今夜我在德令哈”，一淡一咸情人湖相映。',
    naturalLandmark: { name: '可鲁克湖（淡水芦苇湖）与托素湖（咸水微波湖）', description: '两湖一水相连，候鸟水草与荒原戈壁交辉。', tag: '柴达木情人湖' },
    culturalLandmark: { name: '海子诗歌陈列馆与白公山外星人遗址', description: '戈壁深处神秘铁质管状物山洞与现代诗歌圣地。', tag: '海子诗魂' },
    ethnicFeatures: { costumes: '德都蒙古袍配长靴彩带', crafts: '枸杞精酿酿造与海子诗抄竹简', traditions: '德令哈诗歌节、祭敖包盛会', specialty: '柴达木福牛、黑枸杞' },
  }),
  createQinghaiCounty({
    id: 'mangya_shi', name: '茫崖市', prefecture: '海西蒙古族藏族自治州', altitude: 3000,
    mapCoord: { x: -0.75, y: 0.20, elevation: 0.62 }, terrainArchetype: 'saltlake',
    terrainType: '恶魔之眼艾肯泉与翡翠湖水上雅丹',
    terrainDescription: '青海西大门，地热喷涌出红褐色的恶魔之眼，翡翠湖翠绿晶莹。',
    naturalLandmark: { name: '艾肯泉（大地恶魔之眼）与茫崖翡翠湖', description: '含硫泉水喷涌千载如凝固巨眼，翡翠湖透亮如果冻。', tag: '大地恶魔之眼' },
    culturalLandmark: { name: '冷湖石油小镇遗址与俄博梁火星营地', description: '地球上最像火星地貌的风蚀雅丹石林。', tag: '火星营地' },
    ethnicFeatures: { costumes: '石油防风沙大风衣、厚毛皮手套', crafts: '盐晶水晶标本手工镶嵌', traditions: '火星基地星空观测会', specialty: '茫崖金黄枸杞、风干牦牛肉' },
  }),
  createQinghaiCounty({
    id: 'wulan_xian', name: '乌兰县', prefecture: '海西蒙古族藏族自治州', altitude: 3000,
    mapCoord: { x: -0.15, y: 0.10, elevation: 0.60 }, terrainArchetype: 'saltlake',
    terrainType: '茶卡天空之镜与哈里哈图原始林海',
    terrainDescription: '“天空之镜”茶卡盐湖水天一色，白盐胜雪，白云倒映湖面。',
    naturalLandmark: { name: '茶卡盐湖（天空之镜）国家4A级奇观', description: '赤足漫步白色盐沼，湖面如明镜倒映无垠苍穹。', tag: '天空之镜茶卡' },
    culturalLandmark: { name: '茶卡百年小火车与古法采盐遗址', description: '沿铁轨驶入盐湖深处的盐业历史长卷。', tag: '盐湖小火车' },
    ethnicFeatures: { costumes: '红裙白巾（拍照名装）与蒙古质朴长袍', crafts: '天然大青盐热敷盐包压制技艺', traditions: '茶卡祭盐湖神大典', specialty: '茶卡大青盐、茶卡贡羊' },
  }),
  createQinghaiCounty({
    id: 'dulan_xian', name: '都兰县', prefecture: '海西蒙古族藏族自治州', altitude: 3180,
    mapCoord: { x: -0.25, y: 0.05, elevation: 0.64 }, terrainArchetype: 'gobi',
    terrainType: '吐蕃古墓群九层妖塔与热水古丝绸之路',
    terrainDescription: '柴达木古丝绸之路咽喉，地下埋藏吐谷浑与吐蕃豪华古陵。',
    naturalLandmark: { name: '香日德班禅行辕绿洲与海寺花海', description: '瀚海戈壁深处的清幽泉林绿洲。', tag: '瀚海绿洲香日德' },
    culturalLandmark: { name: '热水墓群（传说的九层妖塔古墓）', description: '全国十大考古发现，出土大量中亚丝织品与金银器。', tag: '九层妖楼热水墓' },
    ethnicFeatures: { costumes: '吐谷浑古风盘金刺绣长袍', crafts: '金银丝编织手链', traditions: '蒙古德都长调民歌节', specialty: '都兰枸杞、柴达木枸杞酒' },
  }),
  createQinghaiCounty({
    id: 'tianjun_xian', name: '天峻县', prefecture: '海西蒙古族藏族自治州', altitude: 3400,
    ethnicGroup: '藏族',
    mapCoord: { x: -0.12, y: 0.18, elevation: 0.68 }, terrainArchetype: 'canyon',
    terrainType: '天峻石林怪石奇峰与织合玛高山草场',
    terrainDescription: '天峻山如神笔峰插云天，天然喀斯特石林如百兽列阵。',
    naturalLandmark: { name: '天峻山风景名胜区与天然石林', description: '奇石嶙峋突兀，高山草场水草丰盛。', tag: '天峻奇石林' },
    culturalLandmark: { name: '卢日朗岩画与秀角寺古殿', description: '青海高原罕见的新石器晚期摩崖石刻。', tag: '古代石刻岩画' },
    ethnicFeatures: { costumes: '藏式毛皮大袍配纯银嵌松石马鞭', crafts: '手工藏靴缝纫技艺', traditions: '智合玛赛马会', specialty: '天峻藏羊肉、天然干奶酪' },
  }),
  createQinghaiCounty({
    id: 'dachaidan', name: '大柴旦行政委员会', prefecture: '海西蒙古族藏族自治州', altitude: 3170,
    mapCoord: { x: -0.40, y: 0.28, elevation: 0.64 }, terrainArchetype: 'saltlake',
    terrainType: '大柴旦翡翠湖琉璃群池与红崖火星谷',
    terrainDescription: '由数十个深浅不一的翡翠色盐池组成，晶莹如镶嵌在戈壁的翡翠。',
    naturalLandmark: { name: '大柴旦翡翠湖自然景区', description: '形态各异的盐池在阳光下呈现青绿、浅黄与宝蓝交错。', tag: '高原大翡翠湖' },
    culturalLandmark: { name: '大柴旦温泉与柴达木早期探险先锋碑', description: '高原地热自涌泉与地质勘探丰碑。', tag: '柴达木先锋碑' },
    ethnicFeatures: { costumes: '地质探险防风羽绒装配工装靴', crafts: '硼酸晶体标本手工镶嵌', traditions: '翡翠湖星空露营嘉年华', specialty: '大柴旦雪山冷矿泉、戈壁风干羊' },
  }),
];
