import { Item, NPC, DialogueNode, Quest, InteractiveObject, ZoneConfig, ZoneId } from '../types';

export const ZONES: Record<ZoneId, ZoneConfig> = {
  meadow: {
    id: 'meadow',
    name: '扁都口 · 祁连草场',
    title: '丝路咽喉 · 绿草如茵与白雪相映',
    altitude: 2850,
    baseTempDrain: 0.05,
    weather: 'clear',
    description: '扁都口地处祁连山峡谷之中，绿草茵茵，经幡翻卷。远处主峰雪线在云端若隐若现。',
    bgPalette: {
      skyTop: '#3b82f6',
      skyBottom: '#93c5fd',
      mountainFar: '#cbd5e1',
      mountainMid: '#64748b',
      ground: '#3f6212',
      accent: '#eab308',
    },
    features: ['氈房', '草场牦牛', '转经玛尼堆', '暖心营火'],
  },
  danxia: {
    id: 'danxia',
    name: '张掖丹霞 · 红岩烽燧',
    title: '奇峰耸翠 · 汉唐丝路残垣',
    altitude: 3300,
    baseTempDrain: 0.09,
    weather: 'mist',
    description: '层叠赭红的山岩如同大地翻滚的锦缎。古丝绸之路的烽燧在呼啸的风沙与薄雾中伫立千年。',
    bgPalette: {
      skyTop: '#7c2d12',
      skyBottom: '#fdba74',
      mountainFar: '#9a3412',
      mountainMid: '#c2410c',
      ground: '#78350f',
      accent: '#fb923c',
    },
    features: ['丹霞层岩', '古汉唐烽燧', '风鸣石碑', '碎石荒径'],
  },
  forest: {
    id: 'forest',
    name: '祁连冷杉 · 雪涧幽谷',
    title: '苍茫林海 · 暴雪呼啸之境',
    altitude: 3820,
    baseTempDrain: 0.18,
    weather: 'blizzard',
    description: '高达数十丈的冷杉披挂厚重冰霜。狂暴的风雪在此处呼号盘旋，刺骨严寒不断吞噬着旅者的体温。',
    bgPalette: {
      skyTop: '#1e293b',
      skyBottom: '#64748b',
      mountainFar: '#94a3b8',
      mountainMid: '#334155',
      ground: '#e2e8f0',
      accent: '#0284c7',
    },
    features: ['千年古冷杉', '冰封溪涧', '悬崖雪莲', '避风古穴'],
  },
  glacier: {
    id: 'glacier',
    name: '八一冰川 · 天境圣峰',
    title: '万载玄冰 · 祁连圣灵止境',
    altitude: 4680,
    baseTempDrain: 0.28,
    weather: 'light_snow',
    description: '高耸入云的万古冰川如银白玉屏，纯净浩荡。圣坛中央的“冰川之眼”隐隐闪耀着山脉的本源脉动。',
    bgPalette: {
      skyTop: '#0f172a',
      skyBottom: '#38bdf8',
      mountainFar: '#f8fafc',
      mountainMid: '#7dd3fc',
      ground: '#bae6fd',
      accent: '#38bdf8',
    },
    features: ['万古冰川瀑', '冰川之眼圣坛', '雪豹守护灵', '极境云海'],
  },
};

export const INITIAL_INVENTORY: Item[] = [
  {
    id: 'butter_tea',
    name: '热腾腾的酥油茶',
    category: 'food',
    icon: '🍵',
    description: '浓郁醇香的酥油与砖茶慢熬而成。饮下后四肢百骸回暖，大幅提升体温与御寒力。',
    count: 2,
    effect: { temp: 3.5, stamina: 30, resistColdSec: 50 },
  },
  {
    id: 'barley_bread',
    name: '青稞炒面干粮',
    category: 'food',
    icon: '🫓',
    description: '高原耐饥的青稞炒面与干饼，食用后快速恢复体力，抵抗旅途劳顿。',
    count: 3,
    effect: { temp: 1.0, stamina: 60 },
  },
  {
    id: 'flint_tinder',
    name: '火镰与红松松枝',
    category: 'tool',
    icon: '🪵',
    description: '祁连老猎人随身携带的引火物，含有易燃的红松油脂，可点燃荒野中的营火。',
    count: 3,
  },
  {
    id: 'parchment_map',
    name: '祁连丝路古羊皮图',
    category: 'relic',
    icon: '📜',
    description: '手绘的祁连古道山势舆图，标注着从扁都口经丹霞红崖，穿冷杉林直达八一冰川的秘径。',
    count: 1,
  },
];

export const NPCS: NPC[] = [
  {
    id: 'abudu',
    name: '阿不都大爷',
    title: '扁都口老牧人',
    zone: 'meadow',
    x: 480,
    y: 350,
    dialogueId: 'abudu_greeting',
    avatarColor: '#b45309',
    icon: '👴',
  },
  {
    id: 'stonekeeper',
    name: '石伯',
    title: '烽燧遗迹守望人',
    zone: 'danxia',
    x: 520,
    y: 330,
    dialogueId: 'stonekeeper_greeting',
    avatarColor: '#c2410c',
    icon: '🧓',
  },
  {
    id: 'zhuoma',
    name: '卓玛',
    title: '高原采药少女',
    zone: 'forest',
    x: 460,
    y: 380,
    dialogueId: 'zhuoma_greeting',
    avatarColor: '#0284c7',
    icon: '👧',
  },
  {
    id: 'mountain_spirit',
    name: '祁连之灵 · 傲雪',
    title: '万古雪山圣兽',
    zone: 'glacier',
    x: 500,
    y: 280,
    dialogueId: 'spirit_greeting',
    avatarColor: '#38bdf8',
    icon: '🐆',
  },
];

export const DIALOGUES: Record<string, DialogueNode> = {
  abudu_greeting: {
    id: 'abudu_greeting',
    speaker: '阿不都大爷',
    title: '扁都口老牧人',
    text: '远方的旅人，欢迎来到巍巍祁连脚下！你看那远处的雪峰，千百年来庇佑着整条河西走廊。不过这山中的气候瞬息万变，越往上走，严寒越是刺骨。你的体温若是跌得太低，连步子都会迈不开！',
    options: [
      {
        text: '大爷，请问如何在这高原险峰中安全探索？',
        nextId: 'abudu_teach_listen',
      },
      {
        text: '我感觉有些冷，能在毡房旁的营火边取暖吗？',
        nextId: 'abudu_warmth',
      },
    ],
  },
  abudu_teach_listen: {
    id: 'abudu_teach_listen',
    speaker: '阿不都大爷',
    title: '扁都口老牧人',
    text: '好孩子，静下心来。我们祁连山的游牧人有一种代代相传的天赋，叫做【听山】。按下【空格键】（或右侧听山圆钮），闭气凝神，你能听见山石的低语、风雪的气脉，甚至发现肉眼看不见的隐秘小道与灵草！拿上这壶刚煮好的酥油茶，快去试试吧！',
    options: [
      {
        text: '多谢阿不都大爷！我定当谨记【听山】之术。',
        action: 'give_item',
        itemPayload: 'butter_tea',
        nextId: 'abudu_quest_hint',
      },
    ],
  },
  abudu_warmth: {
    id: 'abudu_warmth',
    speaker: '阿不都大爷',
    title: '扁都口老牧人',
    text: '快靠近旁边的营火坐下！柴火噼啪一响，整个人就舒坦了。如果出门在外遇到了熄灭的营火，用你的火镰和松木就能重新点燃它！',
    options: [
      {
        text: '好的，我先烤烤火恢复体温！',
        action: 'heal',
      },
    ],
  },
  abudu_quest_hint: {
    id: 'abudu_quest_hint',
    speaker: '阿不都大爷',
    title: '扁都口老牧人',
    text: '如果你打算继续向北攀登，穿过东侧的路口就能抵达【张掖丹霞】。那里有一座汉唐时期的古烽燧，据说藏着上古指引冰川方位的“祁连古铜镜”。',
    options: [
      {
        text: '我知道了，这就前往丹霞探索！',
        action: 'complete_quest',
      },
    ],
  },

  stonekeeper_greeting: {
    id: 'stonekeeper_greeting',
    speaker: '石伯',
    title: '烽燧遗迹守望人',
    text: '咳咳……好久没有行者能徒步走到这丹霞古烽燧了。你看这些赭红的石岩，那是汉家军旅和粟特驼队的足迹风化而成的骨血。最近山中的风脉紊乱，冰川的圣光被浓雾遮蔽了。',
    options: [
      {
        text: '石伯，听说这里藏有能穿透冰川迷雾的“古铜镜”？',
        nextId: 'stonekeeper_mirror',
      },
      {
        text: '这丹霞红岩如此壮美，可有灵异之处？',
        nextId: 'stonekeeper_lore',
      },
    ],
  },
  stonekeeper_mirror: {
    id: 'stonekeeper_mirror',
    speaker: '石伯',
    title: '烽燧遗迹守望人',
    text: '确实就在此地！但它被古代兵将封存在隐秘的风鸣古石中。你必须在烽燧右侧施展【听山】秘法，循着金色共振的声纹，方能唤醒地底的秘匣！',
    options: [
      {
        text: '我明白了，我这就施展【听山】搜寻秘匣！',
        action: 'start_listening',
      },
    ],
  },
  stonekeeper_lore: {
    id: 'stonekeeper_lore',
    speaker: '石伯',
    title: '烽燧遗迹守望人',
    text: '七彩丹霞，乃造化神秀。若你能寻得古铜镜，再穿过西北隘口，便能进入极寒的【冷杉雪谷】。那里风雪暴烈，千万备足御寒之物！',
    options: [
      {
        text: '谨受指点，多谢老伯！',
      },
    ],
  },

  zhuoma_greeting: {
    id: 'zhuoma_greeting',
    speaker: '卓玛',
    title: '高原采药少女',
    text: '阿……阿嚏！好猛烈的暴风雪！我的手脚快冻僵了……我本是来悬崖采摘百年【祁连雪莲】为山下牧民治病的，可这营火被雪扑灭了，火种也打不着……',
    options: [
      {
        text: '姑娘莫慌，我这里有火镰与松柴，我来帮你点燃营火！',
        nextId: 'zhuoma_light_fire',
      },
      {
        text: '喝一口热腾腾的酥油茶吧，先暖暖身子！',
        nextId: 'zhuoma_drink',
      },
    ],
  },
  zhuoma_light_fire: {
    id: 'zhuoma_light_fire',
    speaker: '卓玛',
    title: '高原采药少女',
    text: '呼……太温暖了！营火燃起来，这暴风雪仿佛也不那么可怕了！为了答谢你，我把刚刚采到的这株圣洁【祁连雪莲】送给你。只要用【听山】凝神，你还能在后方崖壁上找到另外的灵草！',
    options: [
      {
        text: '太珍贵了，感谢卓玛！',
        action: 'give_item',
        itemPayload: 'snow_lotus',
        nextId: 'zhuoma_advice',
      },
    ],
  },
  zhuoma_drink: {
    id: 'zhuoma_drink',
    speaker: '卓玛',
    title: '高原采药少女',
    text: '（咕嘟咕嘟……）啊！这酥油茶好醇厚，身子一下子从里到外都热乎起来了！你真是我的救命恩人！',
    options: [
      {
        text: '大家同在祁连行路，互帮互助是应该的。',
        nextId: 'zhuoma_light_fire',
      },
    ],
  },
  zhuoma_advice: {
    id: 'zhuoma_advice',
    speaker: '卓玛',
    title: '高原采药少女',
    text: '再往上就是祁连至高的圣地【八一冰川】了。相传山巅沉睡着守护万灵的雪神。若你想解开冰川之眼的秘密，需要用你在丹霞获得的古铜镜折射晨曦金光！',
    options: [
      {
        text: '多谢卓玛指路，我定会小心行事！',
        action: 'complete_quest',
      },
    ],
  },

  spirit_greeting: {
    id: 'spirit_greeting',
    speaker: '祁连之灵 · 傲雪',
    title: '万古雪山圣兽',
    text: '千百年了，终于有一位带着诚敬之心、怀揣听山之力的凡人登上了圣峰之巅。你手持古铜镜，身覆风雪寒霜，来到这【八一冰川之眼】前。我是祁连万重山峦的化身，掌管着冰川雪融与绿洲生机。',
    options: [
      {
        text: '山神在上，我一路聆听山石与林木的呼唤，此行只为寻得人与雪山的真谛。',
        nextId: 'spirit_choice',
      },
    ],
  },
  spirit_choice: {
    id: 'spirit_choice',
    speaker: '祁连之灵 · 傲雪',
    title: '万古雪山圣兽',
    text: '善哉。冰川之眼已到更迭之期，两道天命摆在你的面前：其一，将古镜归位封印，令冰川万载永固，雪山保持神圣纯净之寂静；其二，引玄冰之灵化作甘冽春融之水，奔流直下，滋养河西千里沃野，开启人与山峦永续共生之通途。旅者，你的抉择是？',
    options: [
      {
        text: '【抉择一】封存圣峰：护佑千载冰川，令祁连圣境永葆纯洁孤绝。',
        action: 'trigger_ending_1',
      },
      {
        text: '【抉择二】丝路春融：化冰泉润泽绿洲，让万物欣荣、人山共生！',
        action: 'trigger_ending_2',
      },
    ],
  },
};

export const QUESTS: Quest[] = [
  {
    id: 'q1',
    title: '第一卷：天境初启 · 聆听群峦',
    description: '在山脚的扁都口草场拜访阿不都大爷，在毡房旁的营火边取暖，掌握祁连游牧古老的【听山】秘术。',
    zone: 'meadow',
    completed: false,
    objective: '靠近阿不都大爷按【E】对话并领悟“听山”',
    rewardText: '习得“听山”秘技，获得热腾腾的酥油茶与青稞干粮。',
  },
  {
    id: 'q2',
    title: '第二卷：丹霞寻古 · 烽燧铜镜',
    description: '前往张掖丹霞红岩岗，拜访守山石伯。在古代烽燧遗迹旁施展【听山】，找到隐秘的青铜秘匣。',
    zone: 'danxia',
    completed: false,
    objective: '前往张掖丹霞，施展【听山】开启古烽燧秘匣',
    rewardText: '获得【祁连辟邪古铜镜】，可穿透极高海拔的暴风迷雾。',
  },
  {
    id: 'q3',
    title: '第三卷：冷杉穿雪 · 绝壁幽兰',
    description: '深入暴风雪肆虐的祁连冷杉林，点燃熄灭的防风营火救助采药少女卓玛，探寻悬崖圣草。',
    zone: 'forest',
    completed: false,
    objective: '在冷杉雪林点燃营火救援卓玛，并采集雪莲',
    rewardText: '获得【万年祁连雪莲】，大幅强化体温抗寒极限。',
  },
  {
    id: 'q4',
    title: '第四卷：冰川圣境 · 山海长卷',
    description: '登顶巍峨的八一冰川，来到冰川之眼圣坛前，面对祁连山神守护灵，作出决定山脉命运的选择。',
    zone: 'glacier',
    completed: false,
    objective: '登上海拔4680m八一冰川圣坛，抉择双结局之一',
    rewardText: '完成祁连冒险史诗，解锁全域风物志与结局画卷。',
  },
];

export const INTERACTIVE_OBJECTS: InteractiveObject[] = [
  // Meadow
  {
    id: 'meadow_fire',
    name: '毡房旁的红松营火',
    type: 'campfire',
    zone: 'meadow',
    x: 360,
    y: 360,
    width: 48,
    height: 48,
    lit: true,
    prompt: '按 [E] 靠近营火取暖休息，恢复体温与体力',
  },
  {
    id: 'meadow_cairn',
    name: '祈福玛尼石堆',
    type: 'prayer_cairn',
    zone: 'meadow',
    x: 680,
    y: 330,
    width: 40,
    height: 40,
    prompt: '按 [E] 献上敬意，向群山祈福安宁',
  },
  {
    id: 'meadow_passage',
    name: '东行峡谷通路（通往张掖丹霞）',
    type: 'passage',
    zone: 'meadow',
    x: 880,
    y: 320,
    width: 50,
    height: 100,
    prompt: '按 [E] 穿越峡谷进入【张掖丹霞】',
  },

  // Danxia
  {
    id: 'danxia_passage_back',
    name: '返回扁都口草场',
    type: 'passage',
    zone: 'danxia',
    x: 50,
    y: 320,
    width: 40,
    height: 100,
    prompt: '按 [E] 返回【扁都口草场】',
  },
  {
    id: 'danxia_fire',
    name: '烽燧避风处的残火',
    type: 'campfire',
    zone: 'danxia',
    x: 380,
    y: 340,
    width: 48,
    height: 48,
    lit: false,
    prompt: '按 [E] 点燃古烽燧营火御寒',
  },
  {
    id: 'danxia_chest',
    name: '古丝路铜匣（藏有祁连古铜镜）',
    type: 'chest',
    zone: 'danxia',
    x: 720,
    y: 310,
    width: 44,
    height: 44,
    discoveredOnlyByListening: true,
    revealed: false,
    collected: false,
    prompt: '按 [E] 开启古铜匣，获取【祁连辟邪古铜镜】',
  },
  {
    id: 'danxia_stele',
    name: '汉将霍去病纪功残碑',
    type: 'stele',
    zone: 'danxia',
    x: 240,
    y: 330,
    width: 36,
    height: 52,
    prompt: '按 [E] 摹读残碑上模糊的古隶书刻字',
  },
  {
    id: 'danxia_passage_next',
    name: '西北风口险道（通往祁连冷杉林）',
    type: 'passage',
    zone: 'danxia',
    x: 880,
    y: 320,
    width: 50,
    height: 100,
    prompt: '按 [E] 迎着风雪踏入【祁连冷杉林】',
  },

  // Forest
  {
    id: 'forest_passage_back',
    name: '返回张掖丹霞',
    type: 'passage',
    zone: 'forest',
    x: 50,
    y: 320,
    width: 40,
    height: 100,
    prompt: '按 [E] 避开暴雪退回【张掖丹霞】',
  },
  {
    id: 'forest_fire',
    name: '卓玛身旁被雪扑灭的营火',
    type: 'campfire',
    zone: 'forest',
    x: 400,
    y: 390,
    width: 48,
    height: 48,
    lit: false,
    prompt: '按 [E] 使用火镰重新生火，为卓玛驱散刺骨严寒',
  },
  {
    id: 'forest_herb',
    name: '绝壁岩缝间的野生祁连雪莲',
    type: 'herb',
    zone: 'forest',
    x: 740,
    y: 280,
    width: 36,
    height: 36,
    discoveredOnlyByListening: true,
    revealed: false,
    collected: false,
    prompt: '按 [E] 攀岩采撷珍稀的【野生祁连雪莲】',
  },
  {
    id: 'forest_passage_next',
    name: '冰川天阶险路（登顶八一冰川）',
    type: 'passage',
    zone: 'forest',
    x: 880,
    y: 320,
    width: 50,
    height: 100,
    prompt: '按 [E] 穿透暴风雪，登顶【八一冰川】',
  },

  // Glacier
  {
    id: 'glacier_passage_back',
    name: '沿冰阶走回冷杉林',
    type: 'passage',
    zone: 'glacier',
    x: 50,
    y: 320,
    width: 40,
    height: 100,
    prompt: '按 [E] 顺冰瀑退回【祁连冷杉林】',
  },
  {
    id: 'glacier_fire',
    name: '圣峰避风石龛常燃古火',
    type: 'campfire',
    zone: 'glacier',
    x: 260,
    y: 340,
    width: 48,
    height: 48,
    lit: true,
    prompt: '按 [E] 靠近神龛圣火，温暖被极寒冰封的身体',
  },
  {
    id: 'glacier_altar',
    name: '冰川之眼圣坛',
    type: 'stele',
    zone: 'glacier',
    x: 680,
    y: 290,
    width: 54,
    height: 60,
    prompt: '按 [E] 凝视散发幽蓝灵光的万古冰川圣眼',
  },
];

export const LORE_ITEMS = [
  {
    title: '地貌万象 · 祁连天脉',
    category: '地理风貌',
    desc: '祁连山自古被称为“天山”，横亘于青海与甘肃之间。它孕育了黑河、疏勒河与石羊河三大水系，若无祁连雪山千古滋润，便无河西走廊张掖、酒泉、武威、敦煌之千里绿洲。',
  },
  {
    title: '听山之语 · 游牧秘传',
    category: '古法秘术',
    desc: '祁连老猎人与放牧者在长达千年的雪域生存中掌握了“听山”之法。在风声停歇的瞬间凝神，可感悟山岩受冻胀裂的声响、暗河水流的微鸣以及雪豹巡游的气息，从而避开雪崩与绝境。',
  },
  {
    title: '丝路烽燧 · 霍去病与张骞',
    category: '历史沉淀',
    desc: '汉武帝元狩二年，骠骑将军霍去病出陇西，鏖战皋兰，逾焉支山千余里，匈奴遂有悲歌：“亡我祁连山，使我六畜不蕃息；失我焉支山，使我妇女无颜色。”丹霞烽燧即为昔日长城外燧警戍守遗存。',
  },
  {
    title: '八一冰川 · 万仞玄玉',
    category: '自然圣境',
    desc: '八一冰川海拔高达4800余米，冰川表面平整如镜，冰崖高达数十米，宛如一条匍匐在地球脊梁上的巨龙，是整个西北内陆最具代表性的极地冰川景观之一。',
  },
];
